local lastEditor
local panelID
local thrownDice = {}
local editing = false

local queuedRolls = {}
local targetMarker = nil
local lastRemove = 0

local diceData = {}
local consts = {}
local rollData = {}
local settings = {}
local diceAreRolling = false
local defaultRoll = ""
local state = 0

local optionsOpen = false
local configuringRollID = 0
local configuringAliases = false

local absoluteTargetPosition = Vector(0,0,0)
local relativeTargetPosition = Vector(0,0,0)

local currentRoll = {}
local currentRollString = ""
local keepingHighest = false
local keepingLowest = false
local countingOnes = false
local countingSixes = false
local dropHighest = false
local dropLowest = false
local suffix = ""
local rolling = ""
local alting = false
local canceling = false
local rollingPlayer = nil
local rollingLabel = ""

local linkingAlias = -1
local dirty = false

local rollHidden = false
local rollingWaitCondition = 0
local autoCleanupWait = 0
local lastClick = 0

local linkingInProgress = nil
local linkingData = nil

local icons = {"Dice_d4", "Dice_d6", "Dice_d8", "Dice_d10", "Dice_d12", "Dice_d20",  "Dice_d20_adv",  "Dice_d20_dis", "Dice_Roll", "Dice_Fate", "Dice_Fate_4",
"Icon_Book", "Icon_Bow", "Icon_Character", "Icon_Checkmark", "Icon_Cloud", "Icon_Diamond", "Icon_Explosion", 
"Icon_Fire", "Icon_Fist", "Icon_Flag", "Icon_Gear", "Icon_Gun", "Icon_Heart", "Icon_HeartBroken", "Icon_Hourglass", 
"Icon_Key", "Icon_PawnDown", "Icon_PawnUp", "Icon_Plus", "Icon_Pointer", "Icon_Pouch", "Icon_Shield",
"Icon_Skull", "Icon_Star", "Icon_Sword", "Icon_Target", "Icon_Vial", "Icon_Wrench"}

function onload(saved_data)
    self.addContextMenuItem("Set roll target", setRollTarget)
    ready = true
    taken = {}
    local loaded_data = {}
    if (saved_data ~= "") then
        loaded_data = JSON.decode(saved_data)
    end
    rollData = loaded_data.rollData or {}

    updateDiceData()
    
    settings = loaded_data.settings or {
        buttonOffset={x=0,y=0},
        buttonWidth=200,
        grid={x=2,y=5},
        relativeTargetPosition={x=0,y=0,z=6},
        absoluteTargetPosition={x=self.getPosition().x,y=self.getPosition().y,z=self.getPosition().z+3},
        rollHeight=1,
        spread=3,
        rollPositionType="Relative",
        linkedGUIDs="",
        aliases={},
        mode="Basic",
        linkedSheet="",
        variablesLocked=true,
        promotedOnly=false,
        rollsLocked=false,
        switchResult=false,
        announceResult=true,
        displayResult=true,
        iconPanelOffset=true,
        verboseResult=false,
        visibility="All"
    }

    onModeChange(nil, settings.mode, 0, true)
    return 1
end

function onObjectLeaveContainer(container, object)
    if (container != self) then return false end
    dirty = true
end

function onObjectDrop(colorName, object)
    if (object == targetMarker) then
        Wait.time(function()
            changeTargetPosition(colorName)
        end, 1)
    end
end

function changeTargetPosition(color)
    if (targetMarker != nil) then
        Player[color].pingTable(targetMarker.getPosition())
        Player[color].broadcast("Dice roll target position set", "White")
        settings.absoluteTargetPosition = targetMarker.getPosition()
        local relativeOffset = targetMarker.getPosition()-self.getPosition()
        local forward = relativeOffset:dot(self.getTransformForward())
        local right = relativeOffset:dot(self.getTransformRight())
        local up = relativeOffset:dot(self.getTransformUp())
        settings.relativeTargetPosition = Vector(right, up, forward)
        destroyObject(targetMarker)
        updateSave()
        targetMarker = nil
    end
end

function setRollTarget(ply, object_position, object)
    if (targetMarker != nil) then
        destroyObject(targetMarker)
        ply.broadcast("Canceled", "White")
        targetMarker = nil
        return
    end
    ply.broadcast("Grab the token and place it where you want dice rolls to land", "White")
    local markerURL = "https://steamusercontent-a.akamaihd.net/ugc/2458480429345457739/4B52CB8CFA067900BA1C198D488591F9C277D34F/"
    targetMarker = spawnObject({
        type = "Custom_Tile",
        position=add(self.getPosition(), Vector(0,3,0)),
        scale=Vector(0.4,0.4,0.4)
    })
    targetMarker.setName("▶ Place me where you want dice to land")
    targetMarker.setColorTint("Black")
    targetMarker.setCustomObject({
        image=markerURL,
        image_bottom=markerURL,
        type=2,
        thickness=0.2,
        stackable=false,
    })
end

function getObjectKeyFromObjectData(data)
    local objectKey = ""
    local rotValues = data.RotationValues
    local valueCount = #rotValues
    
    if (data.Nickname != "") then
        objectKey = "name:"..string.lower(data.Nickname)
    elseif (valueCount > 0) then
        local maxValue = -99999999
        local words = false
        for k, v in pairs(rotValues) do
            if (tonumber(v.Value) == nil) then
                words = true
            else
                if (tonumber(v.Value) > maxValue) then
                    maxValue = tonumber(v.Value)
                end
            end
        end
        if (words) then
            if (data.Nickname == "") then
                print("Dice thrower: Please give this object a name so I know how to select it")
                return nil
            else
                objectKey = "name:"..string.lower(data.Nickname)
            end
        else
            if (valueCount == 1) then
                objectKey = "const:"..maxValue
            else
                objectKey = "die:"..valueCount
            end
        end
    else
        print("Dice thrower: Inserted objects should have a name and/or rotation values")
        return nil
    end
    return objectKey
end

function updateDiceData()
    diceData = {}
    consts = {}
    local containedObjects = self.getData().ContainedObjects
    for _, containedObject in ipairs(containedObjects) do
        local objectKey = getObjectKeyFromObjectData(containedObject)
        containedObject.memo = objectKey
        diceData[objectKey] = containedObject
        if (string.find(objectKey,"const:")) then
            local spl = split(objectKey, ":")
            if (tonumber(spl[2]) != nil) then
                table.insert(consts, tonumber(spl[2]))
            end
        end
    end
    dirty = false
end

function tryObjectEnter(object)
    if (targetMarker == object) then return end
    if (dirty) then updateDiceData() end
    local data = object.getData()
    local objectKey = getObjectKeyFromObjectData(data)
    if (objectKey == nil) then return false end
    -- Object with that key already in bag, eject
    if (diceData[objectKey] != nil) then
        for k, v in pairs(self.getObjects()) do
            if (v.guid == diceData[objectKey].GUID) then
                self.takeObject({guid=v.guid, position=self.getPosition()+self.getTransformForward()*1.5+self.getTransformUp()})
                break
            end
        end
    end
    dirty = true
    return true
end

function updateSave()
    local data_to_save = {rollData=rollData, settings=settings}
    saved_data = JSON.encode(data_to_save)
    self.script_state = saved_data
end

function toggleEdit()
    configuringRollId = 0
    configuringMode = NORMAL
    editing = not editing
    if (not editing) then
        updateSave()
    end
    createUI()
end

function attrId(str)
    return "MarumDiceRoller_"..str
end

function makeDiceButton(tooltip, dice, icon, posx, posy)
    return [[<Button
    class="DiceButton"
    offsetXY="]]..(posx*80).." "..(posy*80-10)..[["
    icon="]]..icon..[["
    tooltip="]]..tooltip..[["
    onClick="]] .. self.guid .. [[/addToRoll"
    id="]]..dice..[["/>]]
end

function makeThingButton(tooltip, dice, text, posx, posy)
    return [[<Button
    class="DiceButton"
    resizeTextForBestFit="True"
    resizeTextMaxSize="32"
    resizeTextMinSize="10"
    offsetXY="]]..(posx*80).." "..(posy*80-10)..[["
    tooltip="]]..tooltip..[["
    onClick="]] .. self.guid .. [[/addToRoll"
    id="]]..dice..[[">]]..text..[[</Button>]]
end

function makeSuffixButton(tooltip, dice, text, posx, posy)
    return [[<Button
    class="DiceButton"
    resizeTextForBestFit="True"
    width="80"
    height="80"
    tooltipOffset="-8"
    resizeTextMaxSize="32"
    resizeTextMinSize="10"
    offsetXY="]]..(posx*80).." "..(posy*80-10)..[["
    tooltip="]]..tooltip..[["
    onClick="]] .. self.guid .. [[/addToRoll"
    id="]]..dice..[[">]]..text..[[</Button>]]
end

function makeModsButton(posx, posy)
    return [[<Button
    class="DiceButton"
    resizeTextForBestFit="True"
    width="80"
    height="40"
    resizeTextMaxSize="16"
    resizeTextMinSize="10"
    tooltipOffset="-8"
    offsetXY="]]..(posx*80).." "..(posy*80-10)..[["
    tooltip="Add a modifier to the roll"
    onClick="]] .. self.guid .. [[/addMod"
    id="ModsButton">Mods</Button>]]
end

function makeNamedObjectButton(posx, posy)
    return [[<Button
    class="DiceButton"
    resizeTextForBestFit="True"
    width="80"
    height="40"
    resizeTextMaxSize="16"
    resizeTextMinSize="10"
    tooltipOffset="-8"
    offsetXY="]]..(posx*80).." "..(posy*80-10)..[["
    tooltip="Add a named object in the bag to the roll"
    onClick="]] .. self.guid .. [[/addNamedObject"
    id="NamedObjectButton">Misc</Button>]]
end

function makeHitRequirementButton(label, hitTarget, posx, posy)
    return [[<Button
    class="DiceButton"
    resizeTextForBestFit="True"
    width="80"
    height="80"
    resizeTextMaxSize="32"
    resizeTextMinSize="10"
    tooltipOffset="-8"
    offsetXY="]]..(posx*80).." "..(posy*80-10)..[["
    tooltip="Set hit target to ]]..label..[["
    onClick="]] .. self.guid .. [[/setHitTarget"
    id="hitRequirement/]]..hitTarget..[[">]]..label..[[</Button>]]
end

function makeD6CountButton(tooltip, label, posx, posy)
    return [[<Button
    class="DiceButton"
    resizeTextForBestFit="True"
    width="80"
    height="80"
    resizeTextMaxSize="32"
    resizeTextMinSize="10"
    tooltipOffset="-8"
    offsetXY="]]..(posx*80).." "..(posy*80-10)..[["
    tooltip="]]..tooltip..[["
    onClick="]] .. self.guid .. [[/setD6Count"
    id="setD6Count">]]..label..[[</Button>]]
end

function makeEditableAliasButton(aliasID, value, dice, text, tooltip, posx, posy)
    local linkedName = "[Missing Object]"
    if (settings.aliases[aliasID].linkedField != nil and settings.aliases[aliasID].linkedField != -1) then
        local obj = getObjectFromGUID(settings.aliases[aliasID].linkedObject)
        if (obj != nil) then
            linkedName = obj.getName()
        end
    end
    return [[<Panel id="alias_]]..aliasID..[[" active="]]..tostring(not configuringAliases)..[["><Button
    class="DiceButton"
    resizeTextForBestFit="True"
    resizeTextMaxSize="32"
    resizeTextMinSize="10"
    padding="8 8 8 8"
    textAlignment="UpperCenter"
    tooltip="]]..tooltip..": "..value..[["
    tooltipPosition="Above"
    offsetXY="]]..(posx*80).." "..(posy*80-30)..[["
    onClick="]] .. self.guid .. [[/addVariableToRoll"
    id="]]..dice..[[">]]..text..[[</Button>
    <Text
        raycastTarget="false"
        id="aliasValue_]]..aliasID..[["
        offsetXY="]]..(posx*80).." "..(posy*80-50)..[["
        width="80"
        height="40"
        resizeTextForBestFit="True"
        resizeTextMaxSize="28"
        resizeTextMinSize="10"
        color="#aaaaaa"
    >]]..value..[[</Text>
    </Panel>
    <Panel id="aliasConfig_]]..aliasID..[[" active="]]..tostring(configuringAliases)..[[">
    <Button
        class="DiceButton"
        resizeTextForBestFit="True"
        resizeTextMaxSize="24"
        resizeTextMinSize="8"
        padding="8 8 8 8"
        height="40"
        textAlignment="UpperCenter"
        tooltipPosition="Above"
        tooltip="]]..tooltip..": "..value..[["
        offsetXY="]]..(posx*80).." "..(posy*80-10)..[["
        onClick="]] .. self.guid .. [[/addVariableToRoll"
        id="]]..dice..[[">]]..text..": "..value..[[</Button>
        <Button
        class="SmallButton"
        height="40"
        width="27"
        iconWidth="25"
        offsetXY="]]..(posx*80-27).." "..(posy*80-50)..[["
        icon="Icon_Text"
        tooltip="Set name and tooltip"
        padding="2 0 1 0"
        tooltipOffset="-8"
        onClick="]] .. self.guid .. [[/setAliasName"
        id="setAliasName/]]..aliasID..[["/>
    <Button
        class="SmallButton"
        height="40"
        width="27"
        iconWidth="25"
        offsetXY="]]..(posx*80).." "..(posy*80-50)..[["
        icon="Dice_Roll"
        padding="2 0 1 0"
        tooltip="Set value"
        tooltipOffset="-8"
        onClick="]] .. self.guid .. [[/setAliasValue"
        id="setAliasValue/]]..aliasID..[["/>
    <Button
        class="SmallButton"
        height="40"
        width="27"
        iconWidth="25"
        offsetXY="]]..(posx*80+27).." "..(posy*80-50)..[["
        icon="Icon_Trashcan"
        padding="2 0 1 0"
        tooltip="Delete"
        tooltipOffset="-8"
        onClick="]] .. self.guid .. [[/deleteAlias"
        id="deleteAlias/]]..aliasID..[["/>
    </Panel>
    ]]
end

function makeAliasButton(aliasID, value, dice, text, tooltip, posx, posy)
    local isLinked = false
    local linkedName = "[Missing Object]"
    if (settings.aliases[aliasID].linkedField != nil and settings.aliases[aliasID].linkedField != -1) then
        isLinked = true
        local obj = getObjectFromGUID(settings.linkedSheet)
        if (obj != nil) then
            linkedName = obj.getName()
        end
    end
    return [[<Panel id="alias_]]..aliasID..[[" active="]]..tostring(not configuringAliases)..[["><Button
    class="DiceButton"
    resizeTextForBestFit="True"
    resizeTextMaxSize="32"
    resizeTextMinSize="10"
    padding="8 8 8 8"
    textAlignment="UpperCenter"
    tooltip="]]..tooltip..": "..value..[["
    tooltipPosition="Above"
    offsetXY="]]..(posx*80).." "..(posy*80-30)..[["
    onClick="]] .. self.guid .. [[/addVariableToRoll"
    id="]]..dice..[[">]]..text..[[</Button>
    <Text
        raycastTarget="false"
        id="aliasValue_]]..aliasID..[["
        offsetXY="]]..(posx*80).." "..(posy*80-50)..[["
        width="80"
        height="40"
        resizeTextForBestFit="True"
        resizeTextMaxSize="28"
        resizeTextMinSize="10"
        color="#aaaaaa"
    >]]..value..[[</Text>
    </Panel>
    <Panel id="aliasConfig_]]..aliasID..[[" active="]]..tostring(configuringAliases)..[[">
    <Button
        class="DiceButton"
        resizeTextForBestFit="True"
        resizeTextMaxSize="24"
        resizeTextMinSize="8"
        padding="8 8 8 8"
        height="40"
        textAlignment="UpperCenter"
        tooltipPosition="Above"
        tooltip="]]..tooltip..": "..value..[["
        offsetXY="]]..(posx*80).." "..(posy*80-10)..[["
        onClick="]] .. self.guid .. [[/addVariableToRoll"
        id="]]..dice..[[">]]..text..": "..value..[[</Button>
    <Button
        active="]]..tostring(not isLinked)..[["
        class="SmallButton"
        height="40"
        width="80"
        iconWidth="25"
        offsetXY="]]..(posx*80).." "..(posy*80-50)..[["
        icon="Dice_Roll"
        padding="27 0 1 0"
        tooltip="Set value"
        tooltipOffset="-8"
        onClick="]] .. self.guid .. [[/setAliasValue"
        id="setAliasValue/]]..aliasID..[["/>
    <Button
        active="]]..tostring(isLinked)..[["
        class="SmallButton"
        height="40"
        width="80"
        iconWidth="25"
        offsetXY="]]..(posx*80).." "..(posy*80-50)..[["
        icon="Icon_Target"
        padding="27 0 1 0"
        tooltip="Linked to ]]..linkedName..[["
        tooltipOffset="-8"
        colors="#60606080|#60606080|#60606080|#60606080"
        onClick="]] .. self.guid .. [[/null"/>
    </Panel>
    ]]
end

function addMod(ply, value, id)
    if (dirty) then updateDiceData() end
    ply.showOptionsDialog("Add a modifier to the roll", {"Dont clear roll", "Keep highest", "Keep lowest", "Drop highest", "Drop lowest", "Proficiency as dice count", "1 additional dice", "Count ones", "Count sixes"},
    function(text, optionID, player_color)
        if (optionID == 1) then addToCurrentRoll("~NoClear", 1)
        elseif (optionID == 2) then addToCurrentRoll("~High", 1)
        elseif (optionID == 3) then addToCurrentRoll("~Low", 1)
        elseif (optionID == 4) then addToCurrentRoll("~dropHigh", 1)
        elseif (optionID == 5) then addToCurrentRoll("~dropLow", 1)
        elseif (optionID == 6) then addToCurrentRoll("~Prof", 1)
        elseif (optionID == 7) then addToCurrentRoll("~Add1Dice", 1)
        elseif (optionID == 8) then addToCurrentRoll("~Count1s", 1)
        elseif (optionID == 9) then addToCurrentRoll("~Count6s", 1) end
    end)
end

function addNamedObject(ply, value, id)
    if (dirty) then updateDiceData() end
    local options = {}
    for k, v in pairs(diceData) do
        local name = v.Nickname
        if (name != "") then
            table.insert(options,name)
        end
    end
    if (#options == 0)then
        ply.showInfoDialog("There are no named objects in the bag. Name an object and put it into the dice thrower.")
    else
        ply.showOptionsDialog("Choose an object.\nYou can add your own named objects to the bag.", options,
        function (text, index, player_color)
            ply.showInputDialog("How many do you want to roll?", "1",
            function(countText, player_color)
                local count = tonumber(countText)
                if (count == nil) then
                    broadcastToColor("Invalid count '"..text.."'", player_color)
                else
                    if (count > 0) then
                        for i=1, count do
                            addToCurrentRoll("("..text..")", 1)
                        end
                    elseif(count < 0) then
                        for i=1, math.abs(count) do
                            addToCurrentRoll("("..text..")", -1)
                        end
                    end
                end
            end)
        end)
    end
end

function setHitTarget(ply, value, id)
    local spl = split(id,"/")
    local requirement = spl[2]
    local alt = value == "-1"
    if (alt) then
        addToCurrentRoll('>'..requirement..'+', 1)
    else
        addToCurrentRoll('>'..requirement..'+', -1)
    end
end

function setD6Count(ply, value, id)
    ply.showInputDialog("Set amount of d6 to roll", function(text, player_color)
        local count = tonumber(text)
        if (count != nil) then
            currentRoll.d6 = count
            updateCurrentRoll()
        else
            broadcastToColor('"'..text.."' is not a valid number", player_color)
        end
    end)
end

function setAliasName(ply, value, id, skipWarning)
    local spl = split(id,"/")
    local aliasID = tonumber(spl[2])
    if (not skipWarning and settings.mode == "Daggerheart" and string.find(string.lower(settings.aliases[aliasID].name), "prof")) then
        ply.showConfirmDialog("This variable is used for proficiency rolls in Daggerheart. Renaming it may disable proficiency rolls. Are you sure?",
        function(player_color)
            Wait.frames(function()
                setAliasName(ply, value, id, true)
            end,1)
        end)
    else
        local name = ""
        ply.showInputDialog("Set variable short name\n(button label)",
        settings.aliases[aliasID].name,
        function(text, player_color)
            name = text
            local tooltip = name
            if (settings.aliases[aliasID].name == name) then
                tooltip = settings.aliases[aliasID].tooltip
            end
            ply.showInputDialog("Set variable full name\n(button tooltip)",
            tooltip,
            function(text, player_color)
                settings.aliases[aliasID].name = name
                settings.aliases[aliasID].tooltip = text
                createUI()
                updateSave()
            end)
        end)
    end
end

function setAliasValue(ply, value, id)
    local spl = split(id,"/")
    local aliasID = tonumber(spl[2])
    local changeValue = function()
        ply.showInputDialog("Set variable value",
        settings.aliases[aliasID].value,
        function(text, player_color)
            settings.aliases[aliasID].value = text
            settings.aliases[aliasID].linkedField = -1
            createUI()
            updateSave()
        end)
    end
    if (settings.linkedSheet != nil and settings.linkedSheet != "") then
        ply.showConfirmDialog("This variable is linked to "..getObjectFromGUID(settings.linkedSheet).getName()..". Do you want to unlink it?",
        changeValue)
    else
        changeValue()
    end
end

function linkAliasToSheet(ply, value, id)
    local spl = split(id,"/")
    local aliasID = tonumber(spl[2])
    linkingAlias = aliasID
    broadcastToColor("Click on the object you want to link "..settings.aliases[aliasID].name.." to (make sure its unlocked)", ply.color)
end

function deleteAlias(ply, value, id)
    local spl = split(id,"/")
    local aliasID = tonumber(spl[2])
    local delete = function() ply.showConfirmDialog("Delete "..settings.aliases[aliasID].name.."?",
        function(player_color)
            broadcastToColor(settings.aliases[aliasID].name.." deleted", player_color)
            table.remove(settings.aliases, aliasID)
            createUI()
            updateSave()
        end)
    end
    if (not skipWarning and settings.mode == "Daggerheart" and string.find(string.lower(settings.aliases[aliasID].name), "prof")) then
        ply.showConfirmDialog("This variable is used for proficiency rolls in Daggerheart. Renaming it will disable proficiency rolls.",
        function(player_color)
            Wait.frames(function()
                delete()
            end,1)
        end)
    else
        delete()
    end
end

function getButtonTextColor(rollID)
    local color = rollData[rollID].color
    local grayscale = 0.299*color.r + 0.587*color.g + 0.114*color.b
    if (grayscale > 0.5) then
        return "#000000"
    else
        return "#ffffff"
    end
end

function createUI()
    checkForLinkedAliasUpdates(false)
    local guid = self.guid
    local adminVisibility = ""
    if (settings.promotedOnly) then
        adminVisibility = [[visibility="Admin"]]
    end
    local visibility = ""
    if (settings.visibility != nil and settings.visibility != "All") then
        visibility = [[
            <Button visibility="]]..settings.visibility..[[|Black"/>
            <Image visibility="]]..settings.visibility..[[|Black"/>
            <Panel visibility="]]..settings.visibility..[[|Black"/>
            <InputField visibility="]]..settings.visibility..[[|Black"/>
        ]]
    end
    local saveRoll = ""
    if (not settings.rollsLocked) then
        saveRoll = [[<Button
                    class="SmallButton"
                    offsetXY="230 -140"
                    icon="Icon_Save"
                    tooltip="Save roll"
                    onClick="]] .. guid .. [[/saveRoll"
                    id="SaveButton"/> ]]
    end
    local resultX = 200
    if (settings.switchResult) then
        resultX = -200
    end
    local iconPanelPos = "0 -190"
    if (settings.iconPanelOffset) then
        iconPanelPos = getRollButtonOffset((settings.grid.x+1)/2)
    end
    local extraRollButtons = [[
        <Button
    class="SmallButton"
    offsetXY="91 -140"
    icon="Icon_Plus"
    tooltip="Add without clearing previous roll"
    onClick="]] .. guid .. [[/additiveRoll"
    id="AdditiveRollButton"/>
    ]]
    
    if (settings.allowHiddenRolls) then
            extraRollButtons = [[<Button
            class="SmallButton"
            offsetXY="90 -170"
            width="60"
            height="60"
            icon="Icon_Plus"
            tooltip="Add without clearing previous roll"
            onClick="]] .. guid .. [[/additiveRoll"
            id="AdditiveRollButton"/>
        <Button
            class="SmallButton"
            offsetXY="90 -110"
            width="60"
            height="60"
            icon="Icon_Hidden"
            tooltip="Hidden roll (only you and DM can see result)"
            onClick="]] .. guid .. [[/hiddenRoll"
        id="HiddenRollButton"/>]]
    end
    self.UI.setXml([[
        <Defaults>
            ]]..visibility..[[
            <Text class="tableLabel" color="#ffffff" fontSize="20" alignment="MiddleRight" tooltipPosition="Below"
            tooltipBackgroundColor="#000000ff"
            tooltipOffset="-8"/>
            <InputField class="tableInput" textColor="#000000" fontSize="20"/>
            <Button tooltipOffset="-25" tooltipBackgroundColor="#000000ff"/>
            <Button
                class="Slot"
                height="80"
                width="]]..settings.buttonWidth..[["
                fontSize="16"
                textColor="#ffffff"
                textOutline="#000000"
                textAlignment="LowerCenter"
                padding="0 1 0 2"
                colors="#000000b0|#2f2f2f80|#3f3f3f80|#1f1f1f80"
                showAnimation="FadeIn"
                hideAnimation="FadeOut"
                animationDuration="0.1"/>
            <Button
                class="SmallButton"
                height="64"
                width="64"
                textColor="#ffffff"
                alignment="MiddleCenter"
                padding="0 1 0 2"
                colors="#1f1f1f|#2f2f2f|#3f3f3f|#1f1f1f"
                tooltipPosition="Below"
                showAnimation="Grow"
                hideAnimation="Shrink"
                animationDuration="0.1"
                tooltipBackgroundColor="#000000ff"/>
            <Button
                class="ConfigureButton"
                height="40"
                width="40"
                textColor="#ffffff"
                iconColor="#ffffff25"
                alignment="MiddleCenter"
                padding="0 1 0 2"
                colors="#1f1f1f40|#2f2f2f40|#3f3f3f40|#1f1f1f40"
                tooltipPosition="Below"
                tooltipOffset="0"
                showAnimation="Grow"
                hideAnimation="Shrink"
                animationDuration="0.1"
                tooltipBackgroundColor="#000000ff"/>
            <Button
                class="OptionButton"
                height="40"
                width="40"
                iconWidth="32"
                textColor="#ffffff"
                iconColor="#ffffff"
                alignment="MiddleCenter"
                padding="4 1 0 2"
                colors="#1f1f1f|#2f2f2f|#3f3f3f|#1f1f1f"
                tooltipPosition="Below"
                tooltipOffset="0"
                showAnimation="Grow"
                hideAnimation="Shrink"
                animationDuration="0.1"
                tooltipBackgroundColor="#000000ff"/>
            <Button
                class="DiceButton"
                height="80"
                width="80"
                textColor="#ffffff"
                alignment="MiddleCenter"
                padding="0 1 0 2"
                showAnimation="Grow"
                hideAnimation="Shrink"
                animationDuration="0.1"
                colors="#1f1f1f|#2f2f2f|#3f3f3f|#1f1f1f"
                tooltipPosition="Below"
                tooltipBackgroundColor="#000000ff"/>
            <Button
                class="RollButton"
                height="80"
                resizeTextForBestFit="True"
                tooltipPosition="Left"
                showAnimation="Grow"
                hideAnimation="Shrink"
                animationDuration="0.1"
                resizeTextMaxSize="32"
                resizeTextMinSize="10"
                alignment="MiddleCenter"/>
        </Defaults>
        <Panel scale="0.5 0.5 0.5">
            ]]..makeSlotIndicators()..[[
            <Panel
            offsetXY = "0 -310"
                id="OptionsPanel"
                color="#18181880"
                width="650"
                height="540"
                showAnimation="FadeIn"
                hideAnimation="FadeOut"
                animationDuration="0.2"
                active="]]..tostring(optionsOpen)..[["
            >
                <Button
                    class="SmallButton"
                    rectAlignment="UpperRight"
                    icon="Icon_Cross"
                    tooltip="Close"
                    height="40"
                    width="40"
                    onClick="]] .. guid .. [[/toggleOptions"
                />

                <TableLayout width="575" height="520" offsetXY="-25 0" cellSpacing="8" cellBackgroundColor="#00000000">
                    <Row>
                        <Cell columnSpan="6"><Button
                            tooltipPosition="Below"
                            fontSize="20"
                            tooltipOffset="-8"
                            icon="Icon_Target"
                            textColor="#ffffff"
                            iconColor="#ffffff"
                            iconWidth="32"
                            tooltip="Spawns a token, place it where you want dice to land"
                            id="ConfigureAliases"
                            onClick="]]..guid..[[/setRollTarget"
                            colors="#1f4f9f|#1f5fcf|#3f3f3f|#1f1f1f"
                        >Set dice landing position</Button></Cell>
                        <Cell columnSpan="3">
                        <Text class="tableLabel"
                        tooltip="Relative: target moves with thrower | Absolute: target is a fixed point in the table"
                        tooltipPosition="Below"
                        tooltipBackgroundColor="#000000ff"
                        tooltipOffset="-8"
                        >Target type</Text></Cell>
                        <Cell columnSpan="3">
                            <Dropdown id="settings/rollPositionType"
                                tooltip="Relative: target moves with thrower | Absolute: target is a fixed point in the table"
                                tooltipPosition="Below"
                                tooltipBackgroundColor="#000000ff"
                                tooltipOffset="-8"
                                onValueChanged="]]..guid..[[/rollTypeOptionSelected"
                            >
                                <Option selected="]]..tostring(settings.rollPositionType=="Relative")..[[">Relative</Option>
                                <Option selected="]]..tostring(settings.rollPositionType=="Absolute")..[[">Absolute</Option>
                            </Dropdown>
                        </Cell>
                    </Row>
                    <Row
                        tooltip="Set the preset for which dice rolls and variables appear in the toolbar"
                        tooltipPosition="Below"
                        tooltipBackgroundColor="#000000ff"
                        tooltipOffset="-8"
                    >
                        <Cell columnSpan="3"><Text class="tableLabel">RPG System</Text></Cell>
                        <Cell columnSpan="9">
                            <Dropdown id="settings/mode" onValueChanged="]]..guid..[[/onModeChange">
                            <Option selected="]]..tostring(settings.mode=="None")..[[">None</Option>
                                <Option selected="]]..tostring(settings.mode=="Basic")..[[">Basic</Option>
                                <Option selected="]]..tostring(settings.mode=="DnD")..[[">DnD</Option>
                                <Option selected="]]..tostring(settings.mode=="Daggerheart")..[[">Daggerheart</Option>
                                <Option selected="]]..tostring(settings.mode=="Daggerheart (v1.3)")..[[">Daggerheart (v1.3)</Option>
                                <Option selected="]]..tostring(settings.mode=="Fate")..[[">Fate</Option>
                                <Option selected="]]..tostring(settings.mode=="Warhammer")..[[">Warhammer</Option>
                            </Dropdown>
                        </Cell>
                    </Row>
                    <Row>
                        <Cell columnSpan="3"><Text class="tableLabel"
                            tooltip="How much randomness is applied to the dice trajectory"
                        >Roll spread</Text></Cell>
                        <Cell columnSpan="3"><Slider id="settings/spread" class="tableInput" tooltip="How much randomness is applied to the dice trajectory" minValue="0" maxValue="6" wholeNumbers="true" value="]]..settings.spread..[[" onValueChanged="]]..guid..[[/onSettingChange" /></Cell>
                        <Cell columnSpan="3"><Text class="tableLabel" tooltip="How high should the dice reach">Roll height</Text></Cell>
                        <Cell columnSpan="3"><Slider id="settings/rollHeight" class="tableInput" tooltip="How high should the dice reach" minValue="0" maxValue="4" wholeNumbers="true" value="]]..settings.rollHeight..[[" onValueChanged="]]..guid..[[/onSettingChange" /></Cell>
                    </Row>
                    <Row>
                        <Cell columnSpan="6"><Toggle id="settings/displayResult" tooltipBackgroundColor="#000000ff" tooltipOffset="-8" tooltipPosition="Below" tooltip="Show result next to the thrower" textColor="#ffffff" fontSize="18" isOn="]]..tostring(settings.displayResult)..[[" onValueChanged="]]..guid..[[/onSettingChangeAndRefresh">Display result</Toggle></Cell>     
                        <Cell columnSpan="6"><Toggle id="settings/promotedOnly" tooltipBackgroundColor="#000000ff" tooltipOffset="-8" tooltipPosition="Below" tooltip="Only the host or promoted players will see the options button" textColor="#ffffff" fontSize="18" isOn="]]..tostring(settings.promotedOnly)..[[" onValueChanged="]]..guid..[[/onSettingChangeAndRefresh">Promoted only</Toggle></Cell>    
                    </Row>
                    <Row>
                        <Cell columnSpan="6"><Toggle id="settings/switchResult" tooltipBackgroundColor="#000000ff" tooltipOffset="-8" tooltipPosition="Below" tooltip="Show extra results (advantage, hope) on the left instead of on the right" textColor="#ffffff" fontSize="18" isOn="]]..tostring(settings.switchResult)..[[" onValueChanged="]]..guid..[[/onSettingChangeAndRefresh">Flip display</Toggle></Cell>     
                        <Cell columnSpan="6"><Toggle id="settings/rollsLocked" tooltipBackgroundColor="#000000ff" tooltipOffset="-8" tooltipPosition="Below" tooltip="Prevent users from editing, creating or deleting rolls" textColor="#ffffff" fontSize="18" isOn="]]..tostring(settings.rollsLocked)..[[" onValueChanged="]]..guid..[[/onSettingChangeAndRefresh">Lock rolls</Toggle></Cell>
                    </Row>
                    <Row>
                        <Cell columnSpan="6"><Toggle id="settings/announceResult" tooltipBackgroundColor="#000000ff" tooltipOffset="-8" tooltipPosition="Below" tooltip="Announce to everyone the result on screen and in chat" textColor="#ffffff" fontSize="18" isOn="]]..tostring(settings.announceResult)..[[" onValueChanged="]]..guid..[[/onSettingChangeAndRefresh">Announce result</Toggle></Cell>
                        <Cell columnSpan="6"><Toggle id="settings/variablesLocked" tooltipBackgroundColor="#000000ff" tooltipOffset="-8" tooltipPosition="Below" tooltip="Users will be able to change variable values, but not change their names, delete them or create new ones" textColor="#ffffff" fontSize="18" isOn="]]..tostring(settings.variablesLocked)..[[" onValueChanged="]]..guid..[[/onSettingChangeAndRefresh">Lock variables</Toggle>
                        <Button class="ConfigureButton"
                            tooltipPosition="Below"
                            fontSize="24"
                            textColor="#ffffff80"
                            tooltip="What are variables?"
                            id="ConfigureAliases"
                            onClick="]]..guid..[[/variableHelp"
                        >?</Button></Cell>
                    </Row>
                    <Row>
                        <Cell columnSpan="6"><Toggle id="settings/verboseResult" tooltipBackgroundColor="#000000ff" tooltipOffset="-8" tooltipPosition="Below" tooltip="Display the result of each die aswell as the total (announcement only)" textColor="#ffffff" fontSize="18" isOn="]]..tostring(settings.verboseResult)..[[" onValueChanged="]]..guid..[[/onSettingChangeAndRefresh">Verbose announced result</Toggle></Cell>
                        <Cell columnSpan="3"
                        tooltip="Hidden zones don't hide UI elements, so you need to set visibility manually"
                        tooltipPosition="Below"
                        tooltipBackgroundColor="#000000ff"
                        tooltipOffset="-8"
                        ><Text class="tableLabel">Visibility</Text></Cell>
                        <Cell columnSpan="3">
                            <Dropdown id="settings/visibility" onValueChanged="]]..guid..[[/onVisibilityChange">
                                <Option selected="]]..tostring(settings.visibility=="All")..[[">All</Option>
                                <Option selected="]]..tostring(settings.visibility=="Black")..[[">Black</Option>
                                <Option selected="]]..tostring(settings.visibility=="White")..[[">White</Option>
                                <Option selected="]]..tostring(settings.visibility=="Brown")..[[">Brown</Option>
                                <Option selected="]]..tostring(settings.visibility=="Red")..[[">Red</Option>
                                <Option selected="]]..tostring(settings.visibility=="Orange")..[[">Orange</Option>
                                <Option selected="]]..tostring(settings.visibility=="Yellow")..[[">Yellow</Option>
                                <Option selected="]]..tostring(settings.visibility=="Green")..[[">Green</Option>
                                <Option selected="]]..tostring(settings.visibility=="Teal")..[[">Teal</Option>
                                <Option selected="]]..tostring(settings.visibility=="Blue")..[[">Blue</Option>
                                <Option selected="]]..tostring(settings.visibility=="Purple")..[[">Purple</Option>
                                <Option selected="]]..tostring(settings.visibility=="Pink")..[[">Pink</Option>
                            </Dropdown>
                        </Cell>
                    </Row>
                    <Row>
                        <Cell columnSpan="6"><Toggle id="settings/allowHiddenRolls" tooltipBackgroundColor="#000000ff" tooltipOffset="-8" tooltipPosition="Below" tooltip="Adds an extra button to make rolls only you and the DM can see" textColor="#ffffff" fontSize="18" isOn="]]..tostring(settings.allowHiddenRolls)..[[" onValueChanged="]]..guid..[[/onSettingChangeAndRefresh">Allow hidden rolls</Toggle></Cell>
                        <Cell columnSpan="6"><Toggle id="settings/autoCleanup" tooltipBackgroundColor="#000000ff" tooltipOffset="-8" tooltipPosition="Below" tooltip="Cleanup the roll after 5 seconds of showing the result" textColor="#ffffff" fontSize="18" isOn="]]..tostring(settings.autoCleanup)..[[" onValueChanged="]]..guid..[[/onSettingChangeAndRefresh">Auto cleanup</Toggle></Cell>
                    </Row>
                    <Row>
                        <Cell columnSpan="12"><Text class="tableLabel" alignment="MiddleLeft" tooltip="Saved rolls appear in a grid. Below are the options to configure that grid.">Saved rolls</Text></Cell>
                    </Row>
                    <Row>
                        <Cell columnSpan="3"><Text class="tableLabel" tooltip="How many buttons fit horizontally in the grid">Columns</Text></Cell>
                        <Cell columnSpan="3"><InputField class="tableInput" tooltip="How many buttons fit horizontally in the grid" id="settings/grid/x" onValueChanged="]]..guid..[[/updateInputField" onEndEdit="]]..guid..[[/onSettingChangeAndRefresh">]]..settings.grid.x..[[</InputField></Cell>
                        <Cell columnSpan="3"><Text class="tableLabel" tooltip="Horizontal displacement of the grid">X Offset</Text></Cell>
                        <Cell columnSpan="3"><InputField class="tableInput" tooltip="Horizontal displacement of the grid" id="settings/buttonOffset/x" onValueChanged="]]..guid..[[/updateInputField" onEndEdit="]]..guid..[[/onSettingChangeAndRefresh">]]..settings.buttonOffset.x..[[</InputField></Cell>
                    </Row>
                    <Row>
                        <Cell columnSpan="3"><Text class="tableLabel" tooltip="How many buttons fit vertically in the grid">Rows</Text></Cell>
                        <Cell columnSpan="3"><InputField class="tableInput" tooltip="How many buttons fit horizontally in the grid" id="settings/grid/y" onValueChanged="]]..guid..[[/updateInputField" onEndEdit="]]..guid..[[/onSettingChangeAndRefresh">]]..settings.grid.y..[[</InputField></Cell>
                        <Cell columnSpan="3"><Text class="tableLabel" tooltip="Vertical displacement of the grid">Y Offset</Text></Cell>
                        <Cell columnSpan="3"><InputField class="tableInput" tooltip="Vertical displacement of the grid" id="settings/buttonOffset/y" onValueChanged="]]..guid..[[/updateInputField" onEndEdit="]]..guid..[[/onSettingChangeAndRefresh">]]..settings.buttonOffset.y..[[</InputField></Cell>
                    </Row>
                    <Row>
                        <Cell columnSpan="3"><Text class="tableLabel" tooltip="How wide should the saved rolls be">Button width</Text></Cell>
                        <Cell columnSpan="3"><InputField class="tableInput" tooltip="How wide should the saved rolls be" id="settings/buttonWidth" onValueChanged="]]..guid..[[/updateInputField" onEndEdit="]]..guid..[[/onSettingChangeAndRefresh">]]..settings.buttonWidth..[[</InputField></Cell>
                        <Cell></Cell>
                        <Cell columnSpan="5"><Toggle id="settings/iconPanelOffset" tooltipBackgroundColor="#000000ff" tooltipOffset="-8" tooltipPosition="Below" tooltip="Whether to apply the grid offset to the Icon menu when choosing the icon" textColor="#ffffff" fontSize="18" isOn="]]..tostring(settings.iconPanelOffset)..[[" onValueChanged="]]..guid..[[/onSettingChangeAndRefresh">Offset icon panel</Toggle></Cell>
                    </Row>
                </TableLayout>
            </Panel>

            <Panel
            offsetXY = "]]..iconPanelPos..[["
                id="IconPanel"
                color="#181818"
                width="650"
                height="260"
                showAnimation="Grow"
                hideAnimation="Shrink"
                animationDuration="0.2"
                active="False"
            >
                <Button
                    class="SmallButton"
                    rectAlignment="UpperRight"
                    icon="Icon_Cross"
                    tooltip="Cancel"
                    height="40"
                    width="40"
                    onClick="]] .. guid .. [[/cancelIcon"
                />
                <Text offsetXY="-240 105" color="#bbbbbb" fontSize="20">Select an Icon</Text>
                <GridLayout cellSize="53 53" offsetXY="0 -50">
                    ]]..makeIconButtons()..[[
                </GridLayout>
            </Panel>

            <Panel
                id="Toolbar"
                active="]]..tostring(not optionsOpen)..[["
                offsetXY="0 50"
            >
                ]]..extraRollButtons..[[
                <Button
                    class="SmallButton"
                    offsetXY="160 -140"
                    icon="Icon_Trashcan"
                    tooltip="Clear roll"
                    onClick="]] .. guid .. [[/clear"
                    id="ClearButton"/> 
                ]]..saveRoll..[[  
                <InputField
                    id="rollDisplay"
                    colors="#1f1f1f|#2f2f2f|#3f3f3f|#1f1f1f"
                    width="260"
                    height="64"
                    offsetXY="-190 -140"
                    textColor="#ffffff"
                    lineType="MultiLineSubmit"
                    onValueChanged="]]..guid..[[/setManualRoll"
                    resizeTextForBestFit="True"
                    resizeTextMaxSize="32"
                    resizeTextMinSize="10"
                    placeholder=" "
                    textAlignment="MiddleCenter"
                    showAnimation="Grow"
                    hideAnimation="Shrink"
                    animationDuration="0.1"
                ></InputField>

                <Button
                    offsetXY="0 -140"
                    height="120"
                    width="120"
                    icon="Dice_Roll"
                    tooltip="◀ Roll"
                    textColor="#ffffff"
                    alignment="MiddleCenter"
                    padding="12 12 12 12"
                    colors="#1f4f9f|#1f5fcf|#3f3f3f|#1f1f1f"
                    tooltipPosition="Left"
                    showAnimation="Grow"
                    hideAnimation="Shrink"
                    animationDuration="0.1"
                    tooltipOffset="-40"
                    onClick="]] .. guid .. [[/roll"
                    id="RollButton"/>

                <Button
                    class="SmallButton"
                    offsetXY="290 -140"
                    icon="Icon_Gear"
                    tooltip="Options"
                    ]]..adminVisibility..[[
                    height="40"
                    width="40"
                    onClick="]] .. guid .. [[/toggleOptions"
                />

                ]]..makeAllDiceButtons()..[[

                ]]..makeAliasButtons()..[[

                ]]..makeRollButtons()..[[   

                ]]..makeSlots()..[[
            </Panel>
        </Panel>
        <Image id="rollingThrobber"
                offsetXY="0 30"
                active="false"
                width="40"
                height="40"
                pivot="0.52 0.48"
                color="#ffffff"
                outline="#000000"
                showAnimation="Grow"
                animationDuration="0.2"
                image="Icon_Gear"
            />
        <Panel id="resultDisplay" offsetXY="0 30" scale="0.5 0.5 0.5">
            <Text id="result"
                fontSize="80"
                active="false"
                color="#ffffff"
                outline="#000000"
                showAnimation="Grow"
                animationDuration="0.2"
            >20
            </Text>
            <Text id="wordsResult"
                fontSize="40"
                active="false"
                color="#ffffff"
                outline="#000000"
                showAnimation="Grow"
                animationDuration="0.2"
            >20
            </Text>
            <Text id="dualityResult"
                offsetXY="]]..resultX..[[ 0"
                active="false"
                fontSize="40"
                color="#ffffff"
                outline="#000000"
                showAnimation="Grow"
                animationDuration="0.2"
            >w/ Hope
            </Text>
        </Panel>
        <Panel id="extraResultDisplay" offsetXY="]]..(resultX/2)..[[ 20" scale="0.5 0.5 0.5">
            <Text
                id="advantageDisplay"
                active="false"
                offsetXY="0 40"
                fontSize="30"
                color="#55ff55"
                outline="#000000"
                showAnimation="Grow"
                animationDuration="0.2"
            >Advantage
            </Text>
            <Text  id="alternativeResult"
            active="false"
                fontSize="30"
                color="#ffffff"
                outline="#000000"
                showAnimation="Grow"
                animationDuration="0.2"
            >(10 and 20)
            </Text>
        </Panel>
    ]])
end

function onSettingChangeAndRefresh(ply, value, id)
    onSettingChange(ply, value, id)
    createUI()
    updateSave()
end

function onSettingChange(ply, value, id)
    local spl = split(id, "/")
    if (#spl == 2) then
        if (value == "True") then
            value = true
        elseif (value == "False") then
            value = false
        end
        settings[spl[2]] = value
    else
        settings[spl[2]][spl[3]] = value
    end
    updateSave()
end

function onVisibilityChange(ply, option, id)
    settings.visibility = option
    createUI()
    updateSave()
end

function onModeChange(ply, option, id, ignoreAliases)
    settings.mode = option
    if (not ignoreAliases) then
        if (option == "DnD") then
            settings.aliases = {
                {name="STR", tooltip="Strength", value="0"},
                {name="DEX", tooltip="Dexterity", value="0"},
                {name="CON", tooltip="Constitution", value="0"},
                {name="INT", tooltip="Intelligence", value="0"},
                {name="WIS", tooltip="Wisdom", value="0"},
                {name="CHA", tooltip="Charisma", value="0"},
                {name="Prof", tooltip="Proficiency", value="2"} 
            }
        elseif (option == "Daggerheart" or option == "Daggerheart (v1.3)") then
            settings.aliases = {
                {name="AGI", tooltip="Agility", value="0"},
                {name="STR", tooltip="Strength", value="0"},
                {name="FIN", tooltip="Finesse", value="0"},
                {name="INS", tooltip="Instinct", value="0"},
                {name="PRE", tooltip="Presence", value="0"},
                {name="KNO", tooltip="Knowledge", value="0"},
                {name="Prof", tooltip="Proficiency", value="1"} 
            }
        else
            settings.aliases = {}
        end
    end
    createUI()
    updateSave()
end

function makeIconButtons()
    local str = [[
        <Button
            colors="#1f1f1f|#2f2f2f|#3f3f3f|#1f1f1f"
            id="ChooseIconButton/none"
            textColor="#ffffff"
            fontSize="16"
            onClick="]]..self.guid..[[/removeIcon">None</Button>
    ]]
    for k, v in pairs(icons) do
        str = str..[[
            <Button
            colors="#1f1f1f|#2f2f2f|#3f3f3f|#1f1f1f"
            icon="]]..v..[["
            id="ChooseIconButton/]]..v..[["
            onClick="]]..self.guid..[[/chooseIcon"/>
        ]]
    end
    return str
end

function makeAllDiceButtons()
    if (settings.mode == "None") then
        return ""
    elseif (settings.mode == "Basic") then
    return makeDiceButton("Add D4", "d4", "Dice_d4", -4, -3)..
    makeDiceButton("Add D6", "d6", "Dice_d6", -3, -3)..
    makeDiceButton("Add D8", "d8", "Dice_d8", -2, -3)..
    makeDiceButton("Add D10", "d10", "Dice_d10", -1, -3)..
    makeDiceButton("Add D12", "d12", "Dice_d12", 0, -3)..
    makeDiceButton("Add D20", "d20", "Dice_d20", 1, -3)..
    makeThingButton("Add 1", "+1", "+1", 2, -3)..
    makeThingButton("Subtract 1", "-1", "-1", 3, -3)..
    makeModsButton(4, -2.75)..
    makeNamedObjectButton(4, -3.25)
    elseif (settings.mode == "Fate") then
    return makeDiceButton("Add Fate roll", "[fate]", "Dice_Fate_4", -1.5, -3)..
    makeThingButton("Add 1", "+1", "+1", -0.5, -3)..
    makeThingButton("Subtract 1", "-1", "-1", 0.5, -3)..
    makeModsButton(1.5, -2.75)..
    makeNamedObjectButton(1.5, -3.25)
    elseif (settings.mode == "DnD") then
    return makeDiceButton("Add D4", "d4", "Dice_d4", -2.5, -4)..
    makeDiceButton("Add D6", "d6", "Dice_d6", -1.5, -4)..
    makeDiceButton("Add D8", "d8", "Dice_d8", -0.5, -4)..
    makeDiceButton("Add D10", "d10", "Dice_d10", -2.5, -3)..
    makeDiceButton("Add D12", "d12", "Dice_d12", -1.5, -3)..
    makeDiceButton("Add D20", "d20", "Dice_d20", -0.5, -3)..
    makeThingButton("Add 1", "+1", "+1", 1.5, -3)..
    makeThingButton("Subtract 1", "-1", "-1", 1.5, -4)..
    makeDiceButton("Add Advantage", "[adv]", "Dice_d20_adv", 0.5, -3)..
    makeDiceButton("Add Disadvantage", "[dis]", "Dice_d20_dis", 0.5, -4)..
    makeModsButton(2.5, -2.75)..
    makeNamedObjectButton(2.5, -3.25)..
    makeDiceButton("D100", "[d100]", "Dice_d100", 2.5, -4)
    elseif (settings.mode == "Daggerheart") then
    return makeDiceButton("Add D4", "d4", "Dice_d4", -2.5, -4)..
    makeDiceButton("Add D6", "d6", "Dice_d6", -1.5, -4)..
    makeDiceButton("Add D8", "d8", "Dice_d8", -0.5, -4)..
    makeDiceButton("Add D10", "d10", "Dice_d10", -2.5, -3)..
    makeDiceButton("Add D12", "d12", "Dice_d12", -1.5, -3)..
    makeDiceButton("Add D20", "d20", "Dice_d20", -0.5, -3)..
    makeThingButton("Add 1", "+1", "+1", 1.5, -3)..
    makeThingButton("Subtract 1", "-1", "-1", 1.5, -4)..
    makeModsButton(2.5, -3.25)..
    makeNamedObjectButton(2.5, -3.75)..
    makeDiceButton("Add Duality dice", "[duality]", "Dice_duality", 0.5, -3)..
    makeDiceButton("D100", "[d100]", "Dice_d100", 0.5, -4)
    elseif (settings.mode == "Daggerheart (v1.3)") then
    return makeDiceButton("Add D4", "d4", "Dice_d4", -3, -4)..
    makeDiceButton("Add D6", "d6", "Dice_d6", -2, -4)..
    makeDiceButton("Add D8", "d8", "Dice_d8", -1, -4)..
    makeDiceButton("Add D10", "d10", "Dice_d10", -3, -3)..
    makeDiceButton("Add D12", "d12", "Dice_d12", -2, -3)..
    makeDiceButton("Add D20", "d20", "Dice_d20", -1, -3)..
    makeThingButton("Add 1", "+1", "+1", 2, -3)..
    makeThingButton("Subtract 1", "-1", "-1", 2, -4)..
    makeModsButton(3, -3.25)..
    makeNamedObjectButton(3, -3.75)..
    makeDiceButton("Add Duality dice", "[duality]", "Dice_duality", 0, -3)..
    makeDiceButton("D100", "[d100]", "Dice_d100", 0, -4)..
    makeDiceButton("Add Advantage", "[dual adv]", "Dice_d20_adv", 1, -3)..
    makeDiceButton("Add Disadvantage", "[dual dis]", "Dice_d20_dis", 1, -4)
    elseif (settings.mode == "Warhammer") then
        return makeDiceButton("Add D6", "d6", "Dice_d6", -2, -3)..
        makeHitRequirementButton("2+", 2, -2, -4)..
        makeHitRequirementButton("3+", 3, -1, -4)..
        makeHitRequirementButton("4+", 4, 0, -4)..
        makeHitRequirementButton("5+", 5, 1, -4)..
        makeHitRequirementButton("6+", 6, 2, -4)..
        makeSuffixButton("Count number of 1s in result", "~Count1s", "1s?", 0, -3)..
        makeSuffixButton("Count number of 6s in result", "~Count6s", "6s?", 1, -3)..
        makeD6CountButton("Manually input the number of D6 to roll", "#D6", -1, -3)..
        makeModsButton(2, -2.75)..
        makeNamedObjectButton(2, -3.25)
    end
end

function makeAliasButtons()
    local yOffset = -5
    if (settings.mode == "Basic") then yOffset = -4 end
    if (settings.mode == "None") then yOffset = -3 end
    local emptyOffset = 0
    if (#settings.aliases == 0) then
        emptyOffset = -20
    end
    local str = ""
    if (not settings.variablesLocked) then
        str = [[
            <Button
                class="ConfigureButton"
                tooltipPosition="Below"
                icon="Icon_Book"
                tooltip="Reload sheet values"
                active="]]..tostring(#settings.aliases > 0 and not configuringAliases and (settings.linkedSheet != nil and settings.linkedSheet != ""))..[["
                offsetXY="]]..(-#settings.aliases/2*80-25+emptyOffset).." "..(yOffset*80-30)..[["
                id="ReloadSheetValues"
                iconWidth="30"
                padding="5 0 0 0"
                onClick="]]..self.guid..[[/checkForLinkedAliasUpdates"
            />
            <Button
                class="ConfigureButton"
                tooltipPosition="Below"
                icon="Icon_Wrench"
                tooltip="Configure variables"
                active="]]..tostring(not configuringAliases)..[["
                offsetXY="]]..(#settings.aliases/2*80+25+emptyOffset).." "..(yOffset*80-30)..[["
                id="ConfigureAliases"
                onClick="]]..self.guid..[[/configureAliases"
            />
            <Button
                class="SmallButton"
                width="60"
                height="60"
                tooltipPosition="Below"
                icon="Icon_Plus"
                tooltip="New variable"
                active="]]..tostring(configuringAliases)..[["
                tooltipOffset="0"
                offsetXY="]]..(#settings.aliases/2*80+40+emptyOffset*2).." "..(yOffset*80-30)..[["
                id="AddAlias"
                onClick="]]..self.guid..[[/newAlias"
            />
            <Button
                class="SmallButton"
                width="40"
                height="40"
                tooltipPosition="Below"
                icon="Icon_Book"
                tooltip="Link with compatible Editable Sheet"
                active="]]..tostring(configuringAliases and (settings.linkedSheet == nil or settings.linkedSheet == ""))..[["
                tooltipOffset="0"
                offsetXY="]]..(-#settings.aliases/2*80-25+emptyOffset*2).." "..(yOffset*80-30)..[["
                iconWidth="30"
                padding="5 0 0 0"
                id="LinkSheet"
                onClick="]]..self.guid..[[/linkSheet"
            />
            <Button
                class="SmallButton"
                width="100"
                height="40"
                tooltipPosition="Below"
                tooltip="Link a variable to the sheet"
                active="]]..tostring(configuringAliases and (settings.linkedSheet != nil and settings.linkedSheet != ""))..[["
                tooltipOffset="0"
                offsetXY="]]..(-#settings.aliases/2*80-60+emptyOffset*2).." "..(yOffset*80-10)..[["
                fontSize="15"
                id="LinkAlias"
                onClick="]]..self.guid..[[/linkAlias"
            >Link variable</Button>
            <Button
                class="SmallButton"
                width="100"
                height="40"
                tooltipPosition="Below"
                tooltip="Unlink sheet"
                active="]]..tostring(configuringAliases and (settings.linkedSheet != nil and settings.linkedSheet != ""))..[["
                tooltipOffset="0"
                offsetXY="]]..(-#settings.aliases/2*80-60+emptyOffset*2).." "..(yOffset*80-50)..[["
                fontSize="15"
                id="UnlinkSheet"
                onClick="]]..self.guid..[[/unlinkSheet"
                >Unlink sheet</Button>
            <Button
                class="SmallButton"
                width="40"
                height="40"
                tooltipPosition="Below"
                icon="Icon_Checkmark"
                tooltip="Accept changes"
                active="]]..tostring(configuringAliases)..[["
                tooltipOffset="0"
                offsetXY="]]..(#settings.aliases/2*80+105+emptyOffset*2).." "..(yOffset*80-30)..[["
                id="FinishConfigureAliases"
                onClick="]]..self.guid..[[/configureAliases"
            />
        ]]
        for k, v in pairs(settings.aliases) do
            str = str..makeEditableAliasButton(k, v.value, "{"..v.name.."}", v.name, v.tooltip, (k-0.5)-#settings.aliases/2, yOffset)
        end
    else
        if (#settings.aliases > 0)then
            str = [[
            <Button
                class="ConfigureButton"
                tooltipPosition="Below"
                icon="Icon_Book"
                tooltip="Reload sheet values"
                active="]]..tostring(not configuringAliases and (settings.linkedSheet != nil and settings.linkedSheet != ""))..[["
                offsetXY="]]..(-#settings.aliases/2*80-25+emptyOffset).." "..(yOffset*80-30)..[["
                id="ReloadSheetValues"
                iconWidth="30"
                padding="5 0 0 0"
                onClick="]]..self.guid..[[/checkForLinkedAliasUpdates"
            /><Button
                class="ConfigureButton"
                tooltipPosition="Below"
                icon="Icon_Wrench"
                tooltip="Configure variables"
                active="]]..tostring(not configuringAliases)..[["
                offsetXY="]]..(#settings.aliases/2*80+25+emptyOffset).." "..(yOffset*80-30)..[["
                id="ConfigureAliases"
                onClick="]]..self.guid..[[/configureAliases"
            />
            <Button
                class="SmallButton"
                width="40"
                height="40"
                tooltipPosition="Below"
                icon="Icon_Checkmark"
                tooltip="Accept changes"
                active="]]..tostring(configuringAliases)..[["
                tooltipOffset="0"
                offsetXY="]]..(#settings.aliases/2*80+25+emptyOffset*2).." "..(yOffset*80-30)..[["
                id="FinishConfigureAliases"
                onClick="]]..self.guid..[[/configureAliases"
            />
            ]]
        end
        for k, v in pairs(settings.aliases) do
            str = str..makeAliasButton(k, v.value, "{"..v.name.."}", v.name, v.tooltip, (k-0.5)-#settings.aliases/2, yOffset)
        end
    end
    return str
end

function variableHelp(ply, value, id)
    ply.showInfoDialog("Variables are labeled numbers or dice that can be added to rolls. Useful for stuff like character stats. Examples: 'STR: 1', or 'DMG: 1d6'")
end

function newAlias(ply, value, id)
    local name = "VAR"
    local value = "0"
    ply.showInputDialog("Set variable short name\n(button label)",
    name,
    function(text, player_color)
        name = text
        local tooltip = name
        if (tooltip == "VAR") then
            tooltip = "Variable"
        end
        ply.showInputDialog("Set variable full name\n(button tooltip)",
        tooltip,
        function(text, player_color)
            tooltip=text,
            ply.showInputDialog("Choose variable value\n(can be any number or dice roll)",
            value,
            function(text, player_color)
                value = text
                table.insert(settings.aliases, {
                    name=name,
                    tooltip=tooltip,
                    value=value,
                    linkedField=-1
                })
                createUI()
                updateSave()
            end)
        end)
    end)
end

function configureAliases(ply, value, id)
    if (lastClick + 0.2 > Time.time) then return else lastClick = Time.time end
    if (configuringAliases) then
        configuringAliases = false
        self.UI.show("ConfigureAliases")
        if (settings.linkedSheet != nil and settings.linkedSheet != "") then
            self.UI.show("ReloadSheetValues")
        end
        self.UI.hide("FinishConfigureAliases")
        self.UI.hide("AddAlias")
        self.UI.hide("LinkAlias")
        self.UI.hide("UnlinkSheet")
        self.UI.hide("LinkSheet")
        for i=1, #settings.aliases do
            self.UI.hide("aliasConfig_"..i)
            self.UI.show("alias_"..i)
        end
    else
        configuringAliases = true
        self.UI.hide("ConfigureAliases")
        self.UI.hide("ReloadSheetValues")
        self.UI.show("FinishConfigureAliases")
        self.UI.show("AddAlias")
        if (settings.linkedSheet != nil and settings.linkedSheet != "") then
            self.UI.show("LinkAlias")
            self.UI.show("UnlinkSheet")
        else
            self.UI.show("LinkSheet")
        end
        for i=1, #settings.aliases do
            self.UI.show("aliasConfig_"..i)
            self.UI.hide("alias_"..i)
        end
    end
end

function removeIcon()
    rollData[configuringRollID].icon = nil
    updateButton(configuringRollID)
    self.UI.hide("IconPanel")
    self.UI.show("Toolbar")
    updateSave()
end

function chooseIcon(ply, value, id)
    local spl = split(id, "/")
    local icon = spl[2]
    rollData[configuringRollID].icon = icon
    updateButton(configuringRollID)
    self.UI.hide("IconPanel")
    self.UI.show("Toolbar")
    updateSave()
end

function cancelIcon()
    self.UI.hide("IconPanel")
    self.UI.show("Toolbar")
end

function clear()
    self.UI.show("ClearButton")
    startLuaCoroutine(self, "clearCoroutine")
end

function clearCoroutine()
    canceling = true
    coroutine.yield(0)
    canceling = false
    clearCurrentRoll()
    removeDice()
    return 1
end

function makeRollButtons()
    local str = ""
    for x=1, settings.grid.x do
        for y=1, settings.grid.y do
            local rollID = x+(y-1)*settings.grid.x
            if (rollData[rollID] != nil) then
                str = str..makeRollButton(rollData[rollID], rollID)
            end
        end
    end
    return str
end

function getRollButtonOffset(slotID, xoffset, yoffset)
    local x = (slotID-1)%settings.grid.x
    local y = math.floor((slotID-1)/settings.grid.x)+1
    if (settings.variablesLocked and #settings.aliases == 0) then
        y = y-1
    end
    return ((x-(settings.grid.x-1)/2)*(settings.buttonWidth+50) + (xoffset or 0) + settings.buttonOffset.x).." "..(-getModeOffset()-y*100 + (yoffset or 0) + settings.buttonOffset.y)
end

function makeSlotIndicators()
    local str = ""
    for x=1, settings.grid.x do
        for y=1, settings.grid.y do
            local slotID = x+(y-1)*settings.grid.x
            str = str..[[
                <Button
                    active="]]..tostring(optionsOpen)..[["
                    width="]]..settings.buttonWidth..[["
                    height="64"
                    class="Slot"
                    colors="#000000b0|#000000b0|#000000b0|#000000b0"
                    offsetXY="]]..getRollButtonOffset(slotID, 0, 50)..[["
                    id="slotIndicator/]]..slotID..[["
                    onClick="]]..self.guid..[[/null"
                ></Button>
            ]]
        end
    end
    return str
end

function makeSlots()
    local str = ""
    for x=1, settings.grid.x do
        for y=1, settings.grid.y do
            local slotID = x+(y-1)*settings.grid.x
            str = str..[[
                <Button
                    active="false"
                    class="Slot"
                    offsetXY="]]..getRollButtonOffset(slotID)..[["
                    id="slot/]]..slotID..[["
                    onClick="]]..self.guid..[[/slotClicked"
                >▶ HERE ◀</Button>
            ]]
        end
    end
    return str
end

function colorToColorBlock(color)
    local c = "rgba("..color.r..","..color.g..","..color.b..",1)"
    local c2 = "rgba("..(color.r*0.8+0.1)..","..(color.g*0.8+0.1)..","..(color.b*0.8+0.1)..",1)"
    return c.."|"..c2.."|"..c2.."|"..c
end

function makeRollButton(roll, rollID)
    local icon = [[icon="Nothing" iconWidth="1"]]
    if(roll.icon != nil and roll.icon != "") then
        icon = [[icon="]]..roll.icon..[[" iconWidth="48"]]
    end
    local colorsString = colorToColorBlock(roll.color)
    local textColor = getButtonTextColor(rollID)
    local width = settings.buttonWidth
    return [[
    <Button
        class="RollButton"
        tooltipPosition="Below"
        ]]..icon..[[
        textColor="]]..textColor..[["
        iconColor="]]..textColor..[["
        width="]]..width..[["
        padding="18 20 5 5"
        offsetXY="]]..getRollButtonOffset(rollID)..[["
        colors="]]..colorsString..[["
        tooltip="Roll ]]..roll.value..[["
        onClick="]] .. self.guid .. [[/rollSavedRoll"
        id="roll/]]..rollID..[["
    >]]..roll.label..[[</Button>
    <Panel
        id="RollButtonPanel_]]..rollID..[["
        offsetXY="]]..getRollButtonOffset(rollID)..[["
    >
    <Button
        class="ConfigureButton"
        tooltipPosition="Below"
        icon="Icon_Wrench"
        active="]]..tostring(not settings.rollsLocked)..[["
        tooltip="Configure ]]..roll.label..[["
        offsetXY="]]..(width/2+20)..[[ 0"
        id="Configure/]]..rollID..[["
        onClick="]]..self.guid..[[/configureSavedRoll"
    />
    </Panel>

    <Panel
        id="RollButtonConfiguration_]]..rollID..[["
        offsetXY="]]..getRollButtonOffset(rollID)..[["
        active="False"
    >
    <Button
        class="OptionButton"
        tooltipPosition="Below"
        icon="Icon_Text"
        offsetXY="]]..(width/2-100)..[[ 20"
        tooltip="Label"
        tooltipOffset="-8"
        id="Text/]]..rollID..[["
        onClick="]]..self.guid..[[/setButtonLabel"
    />
    <Button
        class="OptionButton"
        tooltipPosition="Below"
        icon="Icon_Icon"
        offsetXY="]]..(width/2-60)..[[ 20"
        tooltip="Icon"
        tooltipOffset="-8"
        id="Icon/]]..rollID..[["
        onClick="]]..self.guid..[[/setButtonIcon"
    />
    <Button
        class="OptionButton"
        tooltipPosition="Below"
        icon="Icon_Color"
        offsetXY="]]..(width/2-20)..[[ 20"
        tooltip="Color"
        tooltipOffset="-8"
        id="Color/]]..rollID..[["
        onClick="]]..self.guid..[[/setButtonColor"
    />
    <Button
        class="OptionButton"
        tooltipPosition="Below"
        icon="Dice_Roll"
        offsetXY="]]..(width/2-100)..[[ -20"
        tooltip="Edit roll"
        tooltipOffset="-8"
        id="Clone/]]..rollID..[["
        onClick="]]..self.guid..[[/setButtonValue"
    />
    <Button
        class="OptionButton"
        tooltipPosition="Below"
        icon="Icon_ArrowCross"
        offsetXY="]]..(width/2-60)..[[ -20"
        tooltip="Move"
        tooltipOffset="-8"
        id="Move/]]..rollID..[["
        onClick="]]..self.guid..[[/moveButton"
    />
    <Button
        class="OptionButton"
        tooltipPosition="Below"
        icon="Icon_Trashcan"
        offsetXY="]]..(width/2-20)..[[ -20"
        tooltip="Delete"
        tooltipOffset="-8"
        id="Delete/]]..rollID..[["
        onClick="]]..self.guid..[[/deleteButton"
    />
    <Button
        class="OptionButton"
        tooltipPosition="Below"
        icon="Icon_Checkmark"
        offsetXY="]]..(width/2+20)..[[ 0"
        tooltip="Accept"
        tooltipOffset="-8"
        id="CloseConfig/]]..rollID..[["
        onClick="]]..self.guid..[[/acceptSavedRollChanges"
    />
    </Panel>
    ]]
end

function setButtonLabel(ply, value, id)
    ply.showInputDialog("Set label",
        rollData[configuringRollID].label,
        function (text, player_color)
            if (configuringRollID == 0) then return end
            rollData[configuringRollID].label = text
            local textColor = getButtonTextColor(configuringRollID)
            self.UI.setAttributes("roll/"..configuringRollID, {
                text=text,
                textColor=textColor
            })
            updateSave()
        end
    )
end

function setButtonValue(ply, value, id)
    ply.showInputDialog("Set value",
        rollData[configuringRollID].value,
        function (text, player_color)
            if (configuringRollID == 0) then return end
            rollData[configuringRollID].value = text
            self.UI.setAttribute("roll/"..configuringRollID, "tooltip", text)
            updateSave()
        end
    )
end

function setButtonColor(ply, value, id)
    ply.showColorDialog(
        rollData[configuringRollID].color,
        function (color, player_color)
            if (configuringRollID == 0) then return end
            rollData[configuringRollID].color = color
            local colorString = colorToColorBlock(color)
            local textColor = getButtonTextColor(configuringRollID)
            self.UI.setAttributes("roll/"..configuringRollID, {
                colors=colorString,
                iconColor=textColor,
                textColor=textColor
            })
            updateSave()
        end
    )
end

function setButtonIcon(ply, value, id)
    self.UI.show("IconPanel")
    self.UI.hide("Toolbar")
end

function moveButton(ply, value, id)
    stage = 1

    for x=1, settings.grid.x do
        for y=1, settings.grid.y do
            local slotID = x+(y-1)*settings.grid.x
            local text = "▶ MOVE HERE ◀"
            if (slotID == configuringRollID) then
                text = "- CANCEL -"
            elseif (rollData[slotID] != nil) then
                text = "▶ SWAP ◀"
            end
            self.UI.setAttributes("slot/"..slotID, {
                text=text,
                textColor="#ffffff"
            })
            self.UI.show("slot/"..slotID)
        end
    end
end

function copyButton(ply, value, id)
    stage = 2

    for x=1, settings.grid.x do
        for y=1, settings.grid.y do
            local slotID = x+(y-1)*settings.grid.x
            local text = "▶ PASTE HERE ◀"
            if (slotID == configuringRollID) then
                text = "- CANCEL -"
            elseif (rollData[slotID] != nil) then
                text = "!! OVERWRITE !!"
            end
            self.UI.setAttributes("slot/"..slotID, {
                text=text,
                textColor="#ffffff"
            })
            self.UI.show("slot/"..slotID)
        end
    end
end

function deleteButton(ply, value, id)
    local spl = split(id, "/")
    local rollID = tonumber(spl[2])
    ply.showConfirmDialog("Delete button?",
    function(player_color)
        rollData[rollID] = nil
        updateSave()
        createUI()
        broadcastToColor("Button deleted", player_color, "White")
    end)
end

function slotClicked(ply, value, id)
    local spl = split(id, "/")
    local rollID = tonumber(spl[2])
    if (stage == 1) then
        if (rollID != configuringRollID) then
            if (rollData[rollID] == nil) then
                rollData[rollID] = rollData[configuringRollID]
                rollData[configuringRollID] = nil
                updateSave()
            else
                local aux = JSON.encode(rollData[rollID])
                rollData[rollID] = JSON.decode(JSON.encode(rollData[configuringRollID]))
                rollData[configuringRollID] = JSON.decode(aux)
                updateSave()
            end
        end
        stage = 0
        createUI()
    elseif(stage == 2) then
        rollData[rollID] = JSON.decode(JSON.encode(rollData[configuringRollID]))
        stage = 0
        createUI()
        updateSave()
    end
end

function saveRoll()
    clearCurrentRoll()
    self.UI.show("SaveButton")
    local vacantID = 0
    local str = currentRollString
    if (currentRollString == "") then
        str = defaultRoll
    end
    if (str == "") then return end
    table.insert(rollData, {
        label=str,
        value=str,
        color={r=1,g=1,b=1}
    })
    updateSave()
    createUI()
end

function toggleOptions()
    optionsOpen = not optionsOpen
    if (optionsOpen) then
        self.UI.show("OptionsPanel")
        self.UI.hide("Toolbar")
    else
        self.UI.show("Toolbar")
        self.UI.hide("OptionsPanel")
    end
    for x=1, settings.grid.x do
        for y=1, settings.grid.y do
            local slotID = x+(y-1)*settings.grid.x
            if (optionsOpen) then
                self.UI.show("slotIndicator/"..slotID)
            else
                self.UI.hide("slotIndicator/"..slotID)
            end
        end
    end
end

function addToRoll(ply, value, id)
    self.UI.show(id)
    if (rolled) then
        rolled = false
        clearCurrentRoll()
    end
    local alt = value == "-1"
    if (alt) then
        addToCurrentRoll(id, 1)
    else
        addToCurrentRoll(id, -1)
    end
end


function roll(ply, value, id)
    if (dirty) then updateDiceData() end
    rollingPlayer = ply
    rollingLabel = ""
    rollHidden = false
    startLuaCoroutine(self, "rollCoroutine")
    self.UI.show("RollButton")
end

function rollCoroutine()
    canceling = true
    coroutine.yield(0)
    canceling = false
    rollDice(currentRollString)
    return 1
end

function hiddenRoll(ply, value, id)
    rollingPlayer = ply
    rollingLabel = ""
    rollHidden = true
    self.UI.show("HiddenRollButton")
    if (ready) then
        rollDice(currentRollString, false)
    end
end

function additiveRoll(ply, value, id)
    rollingPlayer = ply
    rollingLabel = ""
    self.UI.show("AdditiveRollButton")
    if (ready) then
        rollDice(currentRollString, true)
    else
        table.insert(queuedRolls, currentRollString)
    end
end

function addVariableToRoll(ply, value, id)
    if (configuringAliases) then
        configureAliases()
    end
    addToRoll(ply, value, id)
end

function acceptSavedRollChanges(ply,value,id)
    if (lastClick + 0.2 > Time.time) then return else lastClick = Time.time end
    closeRollConfiguration()
end

function rollSavedRoll(ply, value, id)
    local spl = split(id, "/")
    local rollID = tonumber(spl[2])
    rollingPlayer = ply
    rollingLabel = rollData[rollID].label
    if (value == "-2") then
        if (ready) then
            rollDice(rollData[rollID].value, true)
        else
            table.insert(queuedRolls, rollData[rollID].value)
        end
        self.UI.show(id)
    else
        closeRollConfiguration()
        self.UI.show(id)
        queuedRolls = {}
        currentRollString = rollData[rollID].value
        startLuaCoroutine(self, "rollCoroutine")
    end
end

function configureSavedRoll(ply, value, id)
    if (lastClick + 0.2 > Time.time) then return else lastClick = Time.time end
    local spl = split(id, "/")
    local rollID = tonumber(spl[2])
    closeRollConfiguration()
    if (rollID != configuringRollID) then
        configuringRollID = rollID
        updateButton(configuringRollID)
    end
end

function closeRollConfiguration(ply, value, id)
    if (configuringRollID > 0) then
        local closingID = configuringRollID
        configuringRollID = 0
        updateButton(closingID)
    end
end

function getModeOffset()
    if ((tonumber(settings.buttonOffset.x) > 600) or (tonumber(settings.buttonOffset.x) < -600)) then return 280 end
    if (settings.mode == "None") then return 280 end
    if (settings.mode == "Basic") then return 360 end
    return 440
end

function updateButton(id)
    if (rollData[id] == nil) then return end
    local colorString = colorToColorBlock(rollData[id].color)
    local textColor = getButtonTextColor(id)
    local width = settings.buttonWidth
    local resizeTextMaxSize = "32"
    local offsetXY = getRollButtonOffset(id)
    local iconWidth = "1"
    local padding = "18 20 5 5"
    if (id == configuringRollID) then
        width = width-120
        offsetXY= getRollButtonOffset(id, -60)
        resizeTextMaxSize = "24"
        if (rollData[id].icon != nil) then iconWidth = "24" end
        self.UI.show("RollButtonConfiguration_"..id)
        self.UI.hide("RollButtonPanel_"..id)
        padding="0 0 0 0"
    else
        if (rollData[id].icon != nil) then iconWidth = "48" end
        self.UI.hide("RollButtonConfiguration_"..id)
        self.UI.show("RollButtonPanel_"..id)
    end
    self.UI.setAttributes("roll/"..id, {
        width=width,
        offsetXY=offsetXY,
        iconWidth=iconWidth,
        colors=colorString,
        textColor=textColor,
        icon=rollData[id].icon or "Nothing",
        iconColor=textColor,
        resizeTextMaxSize=resizeTextMaxSize,
        padding=padding
    })
end

function setManualRoll(ply, value, id)
    currentRollString = value
    self.UI.SetAttribute(id, "text", value)
    self.UI.setAttribute("rollDisplay", "textColor", "#ffffff")
end

function updateInputField(ply, value, id)
    self.UI.SetAttribute(id, "text", value)
end

function editRoll(args)
    configuringMode = EDITING
    configuringRollId = args.id
    createUI()
end

function chooseColor(args)
    choosingColor = args.id
    createUI()
end

function backToEditing()
    configuringRollId = 0
    configuringMode = NORMAL
    createUI()
end

function actionButton(args)
    if (args.action == CANCEL) then
        configuringRollId = 0
        configuringMode = NORMAL
    else
        configuringRollId = args.id
        configuringMode = args.action
    end
    createUI()
end

function null()
end

function rollTypeOptionSelected(player, option, id)
    settings.rollPositionType = option
    updateSave()
end

function updateCurrentRoll()
    checkForLinkedAliasUpdates(true)
    local validRoll = false
    for k, v in pairs(currentRoll) do
        validRoll = true
        break
    end
    currentRollString = ""
    requirement = ""
    suffix = ""
    if (validRoll) then
        for k, v in pairs(currentRoll) do
            if (k == "+1") then
                if (string.len(currentRollString) > 0) then
                    currentRollString = currentRollString.."+"..v
                else
                    currentRollString = currentRollString..v
                end
            elseif (k == "-1") then
                currentRollString = currentRollString.."-"..v
            elseif (string.sub(k, 1, 1) == "[") then
                if (v > 0 and string.len(currentRollString) > 0) then
                    currentRollString = currentRollString.."+"..k
                else
                    currentRollString = currentRollString..k
                end
            elseif (string.sub(k, 1, 1) == "~") then
                suffix = suffix..k
            elseif (string.sub(k, 1, 1) == ">") then
                currentRequirement = string.sub(k, 2, 1)
                requirement = k
            else
                if (v > 0 and string.len(currentRollString) > 0) then
                    currentRollString = currentRollString.."+"..v..k
                else
                    currentRollString = currentRollString..v..k
                end
            end
        end
        currentRollString = currentRollString..requirement..suffix
    end
    if (currentRollString != "") then
        self.UI.setAttribute("rollDisplay", "textColor", "#ffffff")
    else
        self.UI.setAttribute("rollDisplay", "textColor", "#333333")
    end
    self.UI.setAttribute("rollDisplay","text",currentRollString)
end

function addToCurrentRoll(add, sign)
    if (string.sub(add,1,1) == ">") then
        for k, v in pairs(currentRoll) do
            if (string.sub(k, 1, 1) == ">") then
                currentRoll[k] = nil
                break
            end
        end
        if (sign == 1) then
            currentRoll[add] = 1
        end
    elseif (string.sub(add,1,1) == "[" or string.sub(add,1,1) == "~") then
        if (sign == 1) then
            currentRoll[add] = 1
        else
            currentRoll[add] = nil
        end
    else
        if (sign == -1) then
            if (add == "+1" or add == "-1") then
                if (currentRoll[add] == nil or currentRoll[add] < 1) then
                    return false
                end
            end
        end
        if (currentRoll[add] == nil) then
            currentRoll[add] = sign
        else
            currentRoll[add] = currentRoll[add]+sign
            if (currentRoll[add] == 0) then
                currentRoll[add] = nil
            end
        end
    end
    updateCurrentRoll()
end

function clearCurrentRoll()
    self.UI.hide("result")
    self.UI.hide("wordsResult")
    self.UI.hide("alternativeResult")
    self.UI.hide("dualityResult")
    self.UI.hide("advantageDisplay")
    self.UI.hide("rollingThrobber")
    currentRoll = {}
    if (currentRollString != "") then
        defaultRoll = currentRollString
        self.UI.setAttribute("rollDisplay", "placeholder", defaultRoll)
    end
    updateCurrentRoll()
end

function removeDice(obj, ply, alt)
    if (Time.time < lastRemove+0.1) then return end
    lastRemove = Time.time
    changeTargetPosition(ply)
    Wait.stop(rollingWaitCondition)
    for k, v in pairs(thrownDice) do
        if (v != nil) then
            destroyObject(v)
        end
    end
    thrownDice = {}

    local otherGUIDs = split(settings.linkedGUIDs, " ")
    for k, v in pairs(otherGUIDs) do
        if (v != self.guid) then
            getObjectFromGUID(v).call("removeDice")
        end
    end
end

function rollDice(roll, alt)
    Wait.stop(autoCleanupWait)
    rolling = roll
    alting = alt
    startLuaCoroutine(self, "rollDiceCoroutine")
    local throwTime = Time.time
    if (settings.displayResult and not rollHidden) then
        self.UI.show("rollingThrobber")
    end
    self.UI.hide("result")
    self.UI.hide("wordsResult")
    self.UI.hide("alternativeResult")
    self.UI.hide("advantageDisplay")
    self.UI.hide("dualityResult")
    if (settings.displayResult or settings.announceResult) then
        Wait.stop(rollingWaitCondition)
        rollingWaitCondition = Wait.condition(
            function()
                self.UI.hide("rollingThrobber")
                updateDisplay()
            end,
            function ()
                self.UI.setAttribute("rollingThrobber", "rotation", "0 0 "..-Time.time*360)
                if (Time.time < throwTime + 1) then
                    return false
                end
                for k, v in pairs(thrownDice) do
                    if (v != nil and not v.resting) then return false end
                end
                return true
            end
        )
    end
end

function rollDiceCoroutine()
    clearCurrentRoll()
    if (rolling == "") then
        rolling = defaultRoll
    else
        defaultRoll = rolling
        self.UI.setAttribute("rollDisplay", "textColor", "#333333")
        self.UI.setAttribute("rollDisplay", "placeholder", defaultRoll)
    end
    local velocity = Vector(0, 0, 0)
    local offset = settings.relativeTargetPosition
    if (settings.rollPositionType == "Absolute") then
        local a = settings.absoluteTargetPosition
        offset = Vector(a.x,a.y,a.z)-self.getPosition()
    end
    local g = Physics.getGravity()
    local h = 0.25+settings.rollHeight/4
    velocity = Vector(offset.x/h-g.x*h, offset.y/h-g.y*h, offset.z/h-g.z*h)*0.68
    local spread = settings.spread/2
    local i = 0
    local parsedRoll = parseRollText(rolling)
    local currentRollData = parsedRoll.rollData
    local isAdditive = parsedRoll.isAdditive
    keepingHighest = parsedRoll.keepHighest
    keepingLowest = parsedRoll.keepLowest
    countingOnes = parsedRoll.countOnes
    countingSixes = parsedRoll.countSixes
    droppingHighest = parsedRoll.dropHighest
    droppingLowest = parsedRoll.dropLowest
    if (currentRollData == nil) then
        return 1
    end
    if (#currentRollData == 0) then
        coroutine.yield(0)
        Wait.stop(rollingWaitCondition)
        self.UI.hide("rollingThrobber")
    end
    ready = false
    if (not isAdditive and not alting) then
        removeDice()
    end
    local throws = #currentRollData
    if (settings.rollPositionType == "Relative") then
        velocity = add(self.getTransformRight()*velocity.x, add(self.getTransformUp()*velocity.y, self.getTransformForward()*velocity.z))
    end
    for k, v in pairs(currentRollData) do
        if (self.getQuantity() > 0) then
            local randomVelocity = Vector(velocity.x+math.random(-spread, spread), velocity.y+math.random(-spread, spread), velocity.z+math.random(-spread, spread))

            local spawnedObject = spawnObjectData({
                data=diceData[v.objectKey],
                position=add(self.getPosition(), Vector(0,1.5,0)),
                rotation=self.getRotation()+Vector(0,180,0)
            })
            table.insert(thrownDice, spawnedObject)
            if (canceling) then
                canceling = false
                return 1
            end
            coroutine.yield(0)
            if (canceling) then
                canceling = false
                return 1
            end
            coroutine.yield(0)
            while (spawnedObject == nil or (spawnedObject != nil and spawnedObject.loading_custom)) do
                if (canceling) then
                    canceling = false
                    return 1
                end
                coroutine.yield(0)
            end
            if not spawnedObject.isDestroyed() then
                if (v.forceName != nil) then
                    spawnedObject.setName(v.forceName)
                end
                if (v.append != nil) then
                    spawnedObject.setName(spawnedObject.getName()..v.append)
                end
                spawnedObject.randomize()
                spawnedObject.setVelocity(randomVelocity)
                if (v.sign == -1) then
                    local invertedRotationValues = spawnedObject.getRotationValues()
                    for kk, vv in pairs(invertedRotationValues) do
                        vv.value = -vv.value
                    end
                    spawnedObject.setRotationValues(invertedRotationValues)
                end
                if (rollHidden) then
                    local allPlayers = Player.getColors()
                    local invisibleTo = {}
                    for k, v in pairs(allPlayers) do
                        if (v != rollingPlayer.color and v != "Black") then
                            table.insert(invisibleTo, v)
                        end
                    end
                    spawnedObject.setInvisibleTo(invisibleTo)
                end
            end
        end
        local frames = 6
        while (frames > 0) do
            if (canceling) then
                canceling = false
                return 1
            end
            frames = frames - 1
            coroutine.yield(0)
        end
    end
    ready = true
    if (#queuedRolls > 0) then
        rollDice(queuedRolls[1], true)
        table.remove(queuedRolls, 1)
    end
    return 1
end

function add(a, b)
    return {x=a.x+b.x, y=a.y+b.y, z=a.z+b.z}
end

function parseRollText(inputText)
    local safety = 100
    local rollData = {}
    if (string.sub(inputText, 1, 1) == "~") then
        return rollData
    end
    local isAdditive = false
    local text = inputText
    for k, v in pairs(settings.aliases) do
        local value = tostring(v.value)
        local sanitisedAlias = value:gsub("-", "–")
        sanitisedAlias = sanitisedAlias:gsub("+", "")
        text = text:gsub("{"..v.name.."}", "("..sanitisedAlias..")")
    end
    if (string.sub(text, 1, 1) ~= "-") then
        text = "+"..text
    end
    local rollText = text
    local suffixSplit = split(text, "~")
    local requirement = ""
    currentRequirement = nil
    if (not string.match(text, "~")) then
        if (string.match(text, ">")) then
            local requirementSplit = split(text, ">")
            rollText = requirementSplit[1]
            requirement = requirementSplit[2]
        else
            rollText = suffixSplit[1]
        end
    else
        if (string.match(text, ">")) then
            local requirementSplit = split(text, ">")
            if (string.match(text, "~")) then
                requirementSplit = split(suffixSplit[1], ">")
            end
            rollText = requirementSplit[1]
            requirement = requirementSplit[2]
        else
            rollText = suffixSplit[1]
        end
    end
    if (requirement != "") then
        currentRequirement = tonumber(string.sub(requirement, 1, -1))
    end
    local useProf = false
    local oneAdditionalDice = false
    local keepHighest = false
    local keepLowest = false
    local dropHighest = false
    local dropLowest = false
    local countOnes = false
    local countSixes = false
    for k, v in pairs(suffixSplit) do
        if (v == "Prof") then
            useProf = true
        elseif (v == "Add1Dice") then
            oneAdditionalDice = true
        elseif (v == "NoClear") then
            isAdditive = true
        elseif (v == "High") then
            keepHighest = true
        elseif (v == "Low") then
            keepLowest = true
        elseif (v == "dropHigh") then
            dropHighest = true
        elseif (v == "dropLow") then
            dropLowest = true
        elseif (v == "Count1s") then
            countOnes = true
        elseif (v == "Count6s") then
            countSixes = true
        end
    end
    for str in string.gmatch(rollText, "([+-][^+-]+)") do
        local str = str:gsub("–", "-")
        local amount = 1
        local sign = 1
        if (string.sub(str, 1, 1) == "-") then
            sign = -1
        end
        -- Multiply in parenthesis
        if (string.sub(str,-1) == ")") then
            local rollSplit = split(str, "(")
            if (#rollSplit == 2) then
                amount = tonumber(rollSplit[1])
                if (amount != nil) then
                    count = amount
                    str = string.sub(rollSplit[2], 1, -2)
                end
                if (amount > 0) then
                    str = "+"..str
                else
                    str = "-"..str
                end
            end
        end
        if (string.sub(str, 1, 1) == "+") then
            str = string.sub(str, 2)
        end
        for amo=1, math.abs(amount) do
            if (string.sub(str,1,1) == "[" and string.sub(str,-1) == "]") then
                --Its a special roll
                if (amount > safety) then
                    broadcastToColor("Roll too big!", rollingPlayer.color, "Red")
                    return {}
                else
                    safety = safety - amount
                end
                local special = string.sub(str,2,-2)
                special = string.lower(special)
                if (string.find(special, "dual") and string.find(special, "dis")) then
                    table.insert(rollData, {objectKey="name:hope", sign=sign, forceName="Hope Disadvantage"})
                elseif (string.find(special, "dual") and string.find(special, "adv")) then
                    table.insert(rollData, {objectKey="name:hope", sign=sign, forceName="Hope Advantage"})
                elseif (string.find(special, "dual")) then
                    table.insert(rollData, {objectKey="name:fear", sign=sign, forceName="Fear"})
                    table.insert(rollData, {objectKey="name:hope", sign=sign, forceName="Hope"})
                elseif (string.find(special, "dis")) then
                    table.insert(rollData, {objectKey="die:20", sign=sign, append="disadvantage"})
                elseif (string.find(special, "adv")) then
                    table.insert(rollData, {objectKey="die:20", sign=sign, append="advantage"})
                elseif (string.find(special, "d100")) then
                    table.insert(rollData, {objectKey="name:tens", sign=1})
                    table.insert(rollData, {objectKey="name:ones", sign=1})
                elseif (string.find(special, "fate")) then
                    table.insert(rollData, {objectKey="name:fate", sign=1})
                    table.insert(rollData, {objectKey="name:fate", sign=1})
                    table.insert(rollData, {objectKey="name:fate", sign=1})
                    table.insert(rollData, {objectKey="name:fate", sign=1})
                end
                
            else
                local diceSplit = split(str, "dD")
                local hasD = false
                if (string.match(str, "[dD]")) then
                    hasD = true
                end
                local number = tonumber(str)
                if (number != nil) then
                    --Its a constant number
                    if (number > 0) then
                        while (number > 0) do
                            local highestValidConst = 0
                            for k, v in pairs(consts) do
                                if (v <= number and v > highestValidConst) then
                                    highestValidConst = v
                                end
                            end
                            local const = "const:"..highestValidConst
                            table.insert(rollData, {objectKey=const, sign=sign})
                            number = number-highestValidConst
                            safety = safety - 1
                            if (safety <= 0) then
                                broadcastToColor("Couldn't make roll with the values in the bag", rollingPlayer.color, "Red")
                                return {}
                            end
                        end
                    elseif (number < 0) then
                        while (number < 0) do
                            local lowestValidConst = 0
                            for k, v in pairs(consts) do
                                if (v >= number and v < lowestValidConst) then
                                    lowestValidConst = v
                                end
                            end
                            local const = "const:"..lowestValidConst
                            table.insert(rollData, {objectKey=const, sign=1})
                            number = number-lowestValidConst
                            safety = safety - 1
                            if (safety <= 0) then
                                broadcastToColor("Couldn't make roll with the values in the bag", rollingPlayer.color, "Red")
                                return {}
                            end
                        end
                    elseif (number == 0) then
                        if (diceData["const:0"] != nil) then
                            table.insert(rollData, {objectKey="const:0", sign=sign})
                            safety = safety - 1
                            if (safety <= 0) then
                                broadcastToColor("Roll too big!", rollingPlayer.color, "Red")
                                return {}
                            end
                        end
                    end    
                elseif (not useProf and (hasD and #diceSplit == 2 and tonumber(diceSplit[1]) != nil and tonumber(diceSplit[2]) != nil)) then
                    local count = math.abs(tonumber(diceSplit[1]))
                    local denomination = tonumber(diceSplit[2])
                    if (oneAdditionalDice) then
                        count = count+1
                    end
                    if (count*amount > safety) then
                        broadcastToColor("Roll too big!", rollingPlayer.color, "Red")
                        return {}
                    else
                        safety = safety - count*amount
                    end
                    if (count != nil and denomination != nil) then
                        --Its a dice roll
                        for i=1, count do
                            table.insert(rollData, {objectKey="die:"..denomination, sign=sign})
                        end
                    end
                elseif (hasD and #diceSplit == 1 and tonumber(diceSplit[1])) then
                    --Proficiency roll
                    local count = 1
                    for k, v in pairs(settings.aliases) do
                        if (string.find(string.lower(v.name), "prof")) then
                            count = tonumber(v.value)
                            break
                        end
                    end
                    if (oneAdditionalDice) then
                        count = count+1
                    end
                    local denomination = tonumber(diceSplit[1])
                    if ((count or 1) > safety) then
                        broadcastToColor("Roll too big!", rollingPlayer.color, "Red")
                        return {}
                    else
                        safety = safety - (count or 1)
                    end
                    if (count != nil and denomination != nil) then
                        --Its a dice roll
                        for i=1, count do
                            table.insert(rollData, {objectKey="die:"..denomination, sign=sign})
                        end
                    end
                elseif (useProf and ((#diceSplit == 1 and tonumber(diceSplit[1])) or #diceSplit == 2 and tonumber(diceSplit[1]) and tonumber(diceSplit[2]))) then
                    --Proficiency roll
                    local count = 1
                    if (#diceSplit == 2) then
                        count = tonumber(diceSplit[1])
                    end
                    for k, v in pairs(settings.aliases) do
                        if (string.find(string.lower(v.name), "prof")) then
                            count = count * tonumber(v.value)
                            break
                        end
                    end
                    if (oneAdditionalDice) then
                        count = count+1
                    end
                    local denomination = tonumber(diceSplit[1])
                    if (#diceSplit == 2) then
                        denomination = tonumber(diceSplit[2])
                    end
                    if ((count or 1) > safety) then
                        broadcastToColor("Roll too big!", rollingPlayer.color, "Red")
                        return {}
                    else
                        safety = safety - (count or 1)
                    end
                    if (count != nil and denomination != nil) then
                        --Its a dice roll
                        for i=1, count do
                            table.insert(rollData, {objectKey="die:"..denomination, sign=sign})
                        end
                    end
                else
                    --Its a named roll
                    table.insert(rollData, {objectKey="name:"..string.lower(str), sign=sign})
                end
            end
        end
    end
    return {rollData=rollData, isAdditive=isAdditive, keepHighest=keepHighest, keepLowest=keepLowest, dropHighest=dropHighest, dropLowest=dropLowest, countOnes=countOnes, countSixes=countSixes}
end

function split (inputstr, sep)
    if sep == nil then
            sep = "%s"
    end
    local t={}
    for str in string.gmatch(inputstr, "([^"..sep.."]+)") do
            table.insert(t, str)
    end
    return t
end

-- RESULT DISPLAY
function updateDisplay()
    local result = 0
    local words = {}
    local hope = 0
    local fear = 0
    local highest = -1000
    local lowest = 1000
    local resting = true
    local advantage = false
    local disadvantage = false
    local disadvantageValue = 0
    local advantageValue = 0
    local hopeadvantage = 0
    local hopedisadvantage = 0
    local natural20 = false
    local d20Count = 0
    local d20 = 0
    local bonus = 0
    local constants = 0

    local ones = 0
    local sixes = 0

    local hits = 0
    local misses = 0

    local individualResults = {}

    local dice = false
    local d100Ones = false
    local d100Tens = false

    local function checkIfHitOrMiss(value)
        if (currentRequirement != nil and currentRequirement != "") then
            if (value >= currentRequirement) then
                hits = hits+1
            else
                misses = misses+1
            end
        end
    end

    self.UI.setValue("dualityResult", "")
    for k, v in pairs(thrownDice) do
        if (not v.getLock()) then
            if (v.getValue() != nil) then
                local rotValue = v.getRotationValue()
                local name = string.lower(v.getName())
                
                if (string.find(name, "hope") and string.find(name, "disadv")) then
                    hopedisadvantage = hopedisadvantage + rotValue
                elseif (string.find(name, "hope") and string.find(name, "adv")) then
                    hopeadvantage = hopeadvantage + rotValue
                elseif (string.find(name, "hope")) then
                    hope = hope + rotValue
                    result = result + rotValue
                    table.insert(individualResults, rotValue)
                    checkIfHitOrMiss(rotValue)
                    dice = true
                elseif (string.find(name, "fear")) then
                    fear = fear + rotValue
                    result = result + rotValue
                    table.insert(individualResults, rotValue)
                    checkIfHitOrMiss(rotValue)
                    dice = true
                elseif (string.find(name, "disadv")) then
                    disadvantage = true
                    disadvantageValue = rotValue
                    table.insert(individualResults, rotValue)
                    checkIfHitOrMiss(rotValue)
                elseif (string.find(name, "adv")) then
                    advantage = true
                    advantageValue = rotValue
                    table.insert(individualResults, rotValue)
                    checkIfHitOrMiss(rotValue)
                else
                    if (string.find(string.lower(name), "tens")) then d100Tens = true end
                    if (string.find(string.lower(name), "ones")) then d100Ones = true end
                    if (tonumber(rotValue)) then
                        result = result + rotValue
                        if (#v.getRotationValues() > 1) then
                            highest = math.max(tonumber(rotValue), highest)
                            lowest = math.min(tonumber(rotValue), lowest)
                            if (tonumber(rotValue) == 1) then
                                ones = ones+1
                            elseif (tonumber(rotValue) == 6) then
                                sixes = sixes+1
                            end
                        end
                        table.insert(individualResults, rotValue)
                        checkIfHitOrMiss(rotValue)
                    else
                        if (words[rotValue] == nil) then
                            words[rotValue] = 1
                        else
                            words[rotValue] = words[rotValue]+1
                        end
                    end
                    if (#v.getRotationValues() == 20) then
                        d20 = rotValue
                        d20Count = d20Count+1
                        if (d20Count == 1 and rotValue == 20) then
                            natural20 = true
                        else
                            natural20 = false
                        end
                    else
                        if (tonumber(rotValue)) then
                            if (#v.getRotationValues() == 1) then
                                constants = constants + rotValue
                            else
                                dice = true
                            end
                            bonus = bonus + rotValue
                        end
                    end
                end
                if (not v.resting)then
                    resting = false
                end
            end
        end
    end
    local dualityResult = ""
    local alternativeResult = ""
    self.UI.setValue("advantageDisplay", "")
    if (hope > 0 and fear > 0 and resting) then
        if (hopedisadvantage > 0) then
            if (hopedisadvantage < hope) then
                if (hope == fear) then
                    alternateDuality = "CRIT"
                end
                if (hope > fear) then
                    alternateDuality = "w/Hope"
                end
                if (hope < fear) then
                    alternateDuality = "w/Fear"
                end
                alternativeResult = "(lost "..result.." "..alternateDuality..")"
                result = result-hope+hopedisadvantage
                hope = hopedisadvantage
            else
                local alternateDuality = ""
                if (hopedisadvantage == fear) then
                    alternateDuality = "CRIT"
                end
                if (hopedisadvantage > fear) then
                    alternateDuality = "w/Hope"
                end
                if (hopedisadvantage < fear) then
                    alternateDuality = "w/Fear"
                end
                alternativeResult = "(lost "..(result-hope+hopedisadvantage).." "..alternateDuality..")"
            end
        end

        if (hopeadvantage > 0) then
            if (hopeadvantage == fear or (hopeadvantage > hope and hope != fear)) then
                if (hope == fear) then
                    alternateDuality = "CRIT"
                end
                if (hope > fear) then
                    alternateDuality = "w/Hope"
                end
                if (hope < fear) then
                    alternateDuality = "w/Fear"
                end
                alternativeResult = "(or "..result.." "..alternateDuality..")"
                result = result-hope+hopeadvantage
                hope = hopeadvantage
            else
                local alternateDuality = ""
                if (hopeadvantage == fear) then
                    alternateDuality = "CRIT"
                end
                if (hopeadvantage > fear) then
                    alternateDuality = "w/Hope"
                end
                if (hopeadvantage < fear) then
                    alternateDuality = "w/Fear"
                end
                alternativeResult = "(or "..(result-hope+hopeadvantage).." "..alternateDuality..")"
            end
        end

        if (hope == fear) then
            dualityResult = "CRIT!"
        end
        if (hope > fear) then
            dualityResult = "w/Hope"
        end
        if (hope < fear) then
            dualityResult = "w/Fear"
        end
    end
    if (d100Tens and d100Ones and result == 0) then
        result = 100
    end

    if (keepingHighest) then
        for k, v in pairs(thrownDice) do
            if (v.getValue() != nil) then
                if (#v.getRotationValues() > 1) then
                    v.highlightOn({r=1, g=0, b=0}, 5)
                end
            end
        end
        for k, v in pairs(thrownDice) do
            if (v.getValue() != nil) then
                if (#v.getRotationValues() > 1) then
                    if (v.getValue() == highest) then
                        v.highlightOn({r=0, g=1, b=0}, 5)
                        break
                    end
                end
            end
        end
        result = highest + constants
    elseif (keepingLowest) then
        for k, v in pairs(thrownDice) do
            if (v.getValue() != nil) then
                if (#v.getRotationValues() > 1) then
                    v.highlightOn({r=1, g=0, b=0}, 5)
                end
            end
        end
        for k, v in pairs(thrownDice) do
            if (v.getValue() != nil) then
                if (#v.getRotationValues() > 1) then
                    if (v.getValue() == lowest) then
                        v.highlightOn({r=0, g=1, b=0}, 5)
                        break
                    end
                end
            end
        end
        result = lowest + constants
    end
    if (droppingLowest) then
        for k, v in pairs(thrownDice) do
            if (v.getValue() != nil) then
                if (#v.getRotationValues() > 1) then
                    v.highlightOn({r=0, g=1, b=0}, 5)
                end
            end
        end
        for k, v in pairs(thrownDice) do
            if (v.getValue() != nil) then
                if (#v.getRotationValues() > 1) then
                    if (v.getValue() == lowest) then
                        v.highlightOn({r=1, g=0, b=0}, 5)
                        break
                    end
                end
            end
        end
        result = result - lowest
    end
    if (droppingHighest) then
        for k, v in pairs(thrownDice) do
            if (v.getValue() != nil) then
                if (#v.getRotationValues() > 1) then
                    v.highlightOn({r=0, g=1, b=0}, 5)
                end
            end
        end
        for k, v in pairs(thrownDice) do
            if (v.getValue() != nil) then
                if (#v.getRotationValues() > 1) then
                    if (v.getValue() == highest) then
                        v.highlightOn({r=1, g=0, b=0}, 5)
                        break
                    end
                end
            end
        end
        result = result - highest
    end
    if (keepingHighest and keepingLowest) then
        broadcastToAll("What do you mean 'keep highest' but also 'keep lowest'?")
    end
    if (keepingHighest and droppingHighest) then
        broadcastToAll("What do you mean 'keep highest' but also 'drop highest'?")
    end
    if (keepingLowest and droppingLowest) then
        broadcastToAll("What do you mean 'keep lowest' but also 'drop lowest'?")
    end

    if (advantage) then
        highest = math.max(advantageValue, d20)
        lowest = math.min(advantageValue, d20)
        result = highest+bonus
        removeByValue(individualResults, lowest)
        if (math.max(advantageValue, d20) == 20) then
            natural20 = true
        end
        alternativeResult = "("..(lowest)..", "..(highest)..")"
        self.UI.setAttributes("advantageDisplay", {
            text="Advantage",
            color="#80dd80"
        })
    elseif (disadvantage) then
        highest = math.max(disadvantageValue, d20)
        lowest = math.min(disadvantageValue, d20)
        result = lowest+bonus
        removeByValue(individualResults, highest)
        if (math.min(disadvantageValue, d20) == 20) then
            natural20 = true
        else
            natural20 = false
        end
        alternativeResult = "("..(lowest)..", "..(highest)..")"
        self.UI.setAttributes("advantageDisplay", {
            text="Disadvantage",
            color="#dd8080"
        })
    end

    if (not rollHidden and settings.displayResult) then
        if (result != "") then
            if (currentRequirement == nil) then
                local wordCount = 0
                for k, v in pairs(words) do
                    wordCount = wordCount+1
                end
                if (wordCount == 0) then
                    self.UI.show("result")
                    self.UI.setValue("result", result)
                else
                    local wordStr = ""
                    local i = 0
                    for k, v in pairs(words) do
                        if (i > 0) then
                            if (i == wordCount-1) then
                                wordStr = wordStr.." and "
                            else
                                wordStr = wordStr..", "
                            end
                        end
                        i = i+1
                        if (wordCount == 1 and v == 1) then
                            wordStr = wordStr..k
                        else
                            wordStr = wordStr..v.." "..k
                        end
                        first = false
                    end
                    self.UI.show("wordsResult")

                    if (countingOnes) then
                        wordStr = wordStr.." ("..ones.." ones)"
                    end
                    if (countingSixes) then
                        wordStr = wordStr.." ("..sixes.." sixes)"
                    end

                    if (dice) then
                        self.UI.setValue("wordsResult", result.." with "..wordStr)
                    else
                        self.UI.setValue("wordsResult", wordStr)
                    end
                end
            else
                self.UI.show("wordsResult")
                local hitStr = " successes"
                if (hits == 1) then
                    hitStr = " success"
                end
                local missStr = " misses"
                if (misses == 1) then
                    missStr = " miss"
                end
                local wordStr = ""
                if (countingOnes) then
                    wordStr = wordStr.." ("..ones.." ones)"
                end
                if (countingSixes) then
                    wordStr = wordStr.." ("..sixes.." sixes)"
                end

                if (hits > 0) then
                    if (misses > 0) then
                        self.UI.setValue("wordsResult", hits..hitStr..", "..misses..missStr.." ["..currentRequirement.."+]"..wordStr)
                    else
                        self.UI.setValue("wordsResult", hits..hitStr.." ["..currentRequirement.."+]"..wordStr)
                    end
                else
                    self.UI.setValue("wordsResult", misses..missStr.." ["..currentRequirement.."+]"..wordStr)
                end
            end
        end
        if (natural20) then
            if (advantage) then
                self.UI.show("advantageDisplay")
                self.UI.show("alternativeResult")
                self.UI.setValue("alternativeResult", "Nat 20! ("..(lowest)..", "..(highest)..")")
            elseif (disadvantage) then
                self.UI.show("advantageDisplay")
                self.UI.show("alternativeResult")
                self.UI.setValue("alternativeResult", "Nat 20! ("..(lowest)..", "..(highest)..")")
            else
                self.UI.show("dualityResult")
                self.UI.setValue("dualityResult", "Natural 20!")
            end
        else
            if (alternativeResult != "") then
                self.UI.show("alternativeResult")
                self.UI.setValue("alternativeResult", alternativeResult)
                if (dualityResult != "") then
                    self.UI.show("advantageDisplay")
                    self.UI.setAttributes("advantageDisplay", {
                        text=dualityResult,
                        color="White"
                    })
                end
            else
                if (dualityResult != "") then
                    self.UI.show("dualityResult")
                    self.UI.setValue("dualityResult", dualityResult)
                end
            end
            if (advantage or disadvantage) then
                self.UI.show("advantageDisplay")
            end
        end
    end

    if (settings.announceResult) then
        local announcement = ""
        local append = ": "
        if (rollingLabel != "") then
            append = " "..rollingLabel..": "
        end
        if (currentRequirement == nil) then
            local verboseResult = ""
            if (settings.verboseResult) then
                if (#individualResults > 1) then
                    if (keepingHighest) then
                        if (constants == 0) then
                            verboseResult = "(highest): "
                        elseif(constants > 0) then
                            verboseResult = "(highest, "..highest.."+"..constants.."): "
                        else
                            verboseResult = "(highest, "..highest..constants.."): "
                        end
                    elseif (keepingLowest) then
                        if (constants == 0) then
                            verboseResult = "(lowest): "
                        elseif(constants > 0) then
                            verboseResult = "(lowest, "..lowest.."+"..constants.."): "
                        else
                            verboseResult = "(lowest, "..lowest..constants.."): "
                        end
                    else
                        verboseResult = table.concat(individualResults,"+")
                        verboseResult = string.gsub(verboseResult, "%+%-", "-")
                        verboseResult = verboseResult.." = "
                    end
                    append = " "..verboseResult
                    if (rollingLabel != "") then
                        append = " "..rollingLabel..": ".." "..verboseResult
                    end
                end
            end
            if (countingOnes) then
                result = result.." ("..ones.." ones)"
            end
            if (countingSixes) then
                result = result.." ("..sixes.." sixes)"
            end
            announcement = rollingPlayer.steam_name.." rolled"..append..result
            if (natural20) then
                announcement = rollingPlayer.steam_name.." rolled"..append.."Natural 20! (for a total of "..result..")"
            else
                if (dualityResult != "") then
                    announcement = announcement.." ("..dualityResult..")"
                    if (alternativeResult != "") then
                        announcement = announcement.. " ... "..alternativeResult
                    end
                end
                if (advantage) then
                    announcement = announcement.." ("..(lowest).." & "..(highest).." at advantage)"
                end
                if (disadvantage) then
                    announcement = announcement.." ("..(lowest).." & "..(highest).." at disadvantage)"
                end
            end
            local wordCount = 0
            for k, v in pairs(words) do
                wordCount = wordCount+1
            end
            if (wordCount > 0) then
                local wordStr = ""
                local i = 0
                for k, v in pairs(words) do
                    if (i > 0) then
                        if (i == wordCount-1) then
                            wordStr = wordStr.." and "
                        else
                            wordStr = wordStr..", "
                        end
                    end
                    i = i+1
                    if (wordCount == 1 and v == 1) then
                        wordStr = wordStr..k
                    else
                        wordStr = wordStr..v.." "..k
                    end
                    first = false
                end
                if (dice) then
                    announcement = announcement.." with "..wordStr
                else
                    announcement = rollingPlayer.steam_name.." rolled"..append..wordStr
                end
            end
        else
            local hitStr = " successes"
            if (hits == 1) then
                hitStr = " success"
            end
            local missStr = " misses"
            if (misses == 1) then
                missStr = " miss"
            end
            local verboseDescription = ""
            if (settings.verboseResult) then
                if (string.find(currentRollString, "~")) then
                    local spl = split(currentRollString, "~")
                    verboseDescription = " ("..spl[1]..")"
                else
                    verboseDescription = " ("..currentRollString..")"
                end
                verboseDescription = string.gsub(verboseDescription, ">", "⇒")
                append = verboseDescription..": "
                if (rollingLabel != "") then
                    append = " "..rollingLabel..verboseDescription..": "
                end
            end
            if (hits > 0) then
                if (misses > 0) then
                    announcement = rollingPlayer.steam_name.." rolled"..append..hits..hitStr..", "..misses..missStr.." [Needed "..currentRequirement.."+]"
                else
                    announcement = rollingPlayer.steam_name.." rolled"..append..hits..hitStr.." [Needed "..currentRequirement.."+]"
                end
            else
                announcement = rollingPlayer.steam_name.." rolled"..append..misses..missStr.." [Needed "..currentRequirement.."+]"
            end
            if (countingOnes) then
                announcement = announcement.." ("..ones.." ones)"
            end
            if (countingSixes) then
                announcement = announcement.." ("..sixes.." sixes)"
            end
        end
        if (rollHidden) then
            if (CheckPlayerColorInUse("Black")) then
                broadcastToColor("[Hidden] "..announcement, "Black")
            end
            if (rollingPlayer.color != "Black") then
                broadcastToColor("[Hidden] "..announcement, rollingPlayer.color)
            end
        else
            broadcastToAll(announcement, rollingPlayer.color)
        end
    end

    if (settings.autoCleanup) then
        autoCleanupWait = Wait.time(function()
            removeDice()
            self.UI.hide("result")
            self.UI.hide("wordsResult")
            self.UI.hide("alternativeResult")
            self.UI.hide("dualityResult")
            self.UI.hide("advantageDisplay")
            self.UI.hide("rollingThrobber")
        end, 5)
    end
end

function removeByValue(tbl, value)
    for k, v in pairs(tbl) do
        if (v == value) then
            table.remove(tbl, k)
            break
        end
    end
end

function add(a, b)
    return {x=a.x+b.x, y=a.y+b.y, z=a.z+b.z}
end

function null()
end

function linkSheet(ply, value, id)
    linkingInProgress = ply.color
    broadcastToColor("Ping the Editable Sheet you want to link to (mouse over and press TAB)", ply.color)
end

function unlinkSheet(ply, value, id)
    local name = "[Missing Object]"
    local obj = getObjectFromGUID(settings.linkedSheet)
    if (obj != nil) then
        name = obj.getName()
    end
    ply.showConfirmDialog("Are you sure you want to unlink the dice roller from "..name, function()
        settings.linkedSheet = ""
        for k, v in pairs(settings.aliases) do
            v.linkedField = -1
        end
        broadcastToColor("Sheet unlinked", ply.color)
        createUI()
        updateSave()
    end)
end

function importVariablesFromObject(object)
    if (object.getGUID() != settings.linkedSheet) then
        local json = JSON.decode(object.getGMNotes())
        local newAliases = {}
        if (json.universalDiceRollerData.fields != nil) then
            local inputs = object.getInputs()
            for k, v in pairs(json.universalDiceRollerData.fields) do
                table.insert(newAliases, {
                    name=v[1],
                    tooltip=v[2],
                    value=inputs[tonumber(v[3])].value,
                    linkedField=v[3]
                })
            end
        end
        if (json.universalDiceRollerData.checks != nil) then
            local buttons = object.getButtons()
            for k, v in pairs(json.universalDiceRollerData.checks) do
                local rangeMin = tonumber(v[3])
                local rangeMax = tonumber(v[4])
                local onCharacter = v[5]
                local add = tonumber(v[6])
                local onCount = 0
                for i=rangeMin, rangeMax do
                    if (buttons[i].label == onCharacter) then
                        onCount = onCount+1
                    end
                end
                table.insert(newAliases, {
                    name=v[1],
                    tooltip=v[2],
                    value=tostring(onCount + add or 0),
                    linkedField=0,
                    rangeMin=rangeMin,
                    rangeMax=rangeMax,
                    onCharacter=onCharacter,
                    add=add
                })
            end
        end
        configuringAliases = false
        settings.aliases = newAliases
        settings.linkedSheet = object.getGUID()
        createUI()
        updateSave()
    end
end

function onPlayerPing(ply, pos, object)
    if (linkingInProgress == nil) then return end
    if (linkingInProgress == ply.color) then
        if (object == nil) then
            broadcastToColor("Object not found (make sure the object is unlocked). Canceling link.", ply.color)
            linkingInProgress = nil
        else
            local linkingData = JSON.decode(object.script_state)
            if (linkingData == nil) then
                broadcastToColor("This object has no script. Canceling link.", ply.color)
                linkingInProgress = nil
            else
                if (linkingData.checks != nil and linkingData.fields != nil and linkingData.decals != nil) then
                    settings.linkedSheet = object.getGUID()
                    if (object.getGMNotes() != "") then
                        local json = JSON.decode(object.getGMNotes())
                        if (json != nil) then
                            if (json.universalDiceRollerData != nil) then
                                ply.showConfirmDialog("This object has data for the Universal Dice Roller. Would you like to automatically import it?(This will override the current variables)", function()
                                    importVariablesFromObject(object)
                                    linkingInProgress = nil
                                    broadcastToColor("Data imported", ply.color)                
                                end)
                            end
                        end
                    end
                    broadcastToColor("Successfully linked the dice roller to "..object.getName(), ply.color)
                    self.UI.hide("linkSheet")
                    self.UI.show("unlinkSheet")
                    self.UI.show("linkAlias")
                    updateSave()
                    linkingInProgress = nil
                else
                    broadcastToColor("Linking only works for sheets made with the 'Make Anything Editable' stamp.", ply.color)
                    broadcastToColor("Sheet is not compatible", ply.color)
                    linkingInProgress = nil
                end
            end
        end
    end
end

function linkAlias(ply, value, id)
    local object = getObjectFromGUID(settings.linkedSheet)
    if (object == nil) then
        broadcastToColor("Linked object is missing", ply.color)
        return false
    end
    local data = JSON.decode(object.script_state)
    local aliases = settings.aliases

    local aliasOptions = {}
    for k, v in pairs(aliases) do
        table.insert(aliasOptions, v.tooltip)
    end
    ply.showOptionsDialog("Select a variable to link", aliasOptions,
    function (text, aliasID, player_color)
        local fieldOptions = {}
        for k, v in pairs(data.fields) do
            local name = v.name or "Field #"..k
            table.insert(fieldOptions, name)
        end
        table.insert(fieldOptions,"<Unlink>")

        local column = 0
        local row = 0

        ply.showOptionsDialog("Select a field to link "..aliases[aliasID].tooltip.." to", fieldOptions,
        function (text, fieldID, player_color)
            if (text == "<Unlink>") then -- Unlink
                aliases[aliasID].linkedField = -1
                broadcastToColor("Unlinked "..aliases[aliasID].tooltip, player_color)
                createUI()
                updateSave()
            else
                local finish = function()
                    local name = data.fields[fieldID].name or "Field #"..fieldID
                    local columnText = ""
                    if (column > 0) then
                        columnText = ", column "..column
                    else
                        column = 1
                    end
                    local rowText = ""
                    if (row > 0) then
                        rowText = ", row "..row
                    else
                        row = 1
                    end
                    local inputID = 0
                    for i=1, fieldID-1 do
                        inputID = inputID+data.fields[i].array.x*data.fields[i].array.y
                    end
                    inputID = inputID+(column-1)*data.fields[fieldID].array.y+(row-1)+1
                    aliases[aliasID].linkedField = inputID
                    broadcastToColor("Linked "..aliases[aliasID].tooltip.." to "..name..columnText..rowText, player_color)
                    createUI()
                    updateSave()
                end

                local field = data.fields[fieldID]
                local chooseColumn = function(callback)
                    local o = {}
                    for i=1, tonumber(field.array.x) do
                        table.insert(o, i)
                    end
                    ply.showOptionsDialog("Column", o,
                    function(text, columnID, player_color)
                        column = columnID
                        if (callback != nil) then
                            callback()
                        else
                            finish()
                        end
                    end)
                end
                
                local chooseRow = function(callback)
                    local o = {}
                    for i=1, tonumber(field.array.y) do
                        table.insert(o, i)
                    end
                    ply.showOptionsDialog("Row", o,
                    function(text, rowID, player_color)
                        row = rowID
                        if (callback != nil) then
                            callback()
                        else
                            finish()
                        end
                    end)
                end

                if (tonumber(field.array.x) > 1) then
                    if (tonumber(field.array.y) > 1) then
                        chooseColumn(chooseRow)
                    else
                        chooseColumn()
                    end
                else
                    if (tonumber(field.array.y) > 1) then
                        chooseRow()
                    else
                        finish()
                    end
                end
            end
        end)
    end)
end

function checkForLinkedAliasUpdates(updateIfDirty)
    if (settings.linkedSheet != nil and settings.linkedSheet != "") then
        local obj = getObjectFromGUID(settings.linkedSheet)
        if (obj == nil) then
            settings.linkedSheet = ""
        else
            local inputs = obj.getInputs()
            local buttons = obj.getButtons()
            local dirtyAlias = false
            for k, v in pairs(settings.aliases) do
                if (v.linkedField != nil and v.linkedField >= 0) then
                    if (v.onCharacter != nil) then
                        if (buttons != nil) then
                            local onCount = 0
                            for i=v.rangeMin, v.rangeMax do
                                if (buttons[i].label == v.onCharacter) then
                                    onCount = onCount+1
                                end
                            end
                            if (v.add != nil) then
                                onCount = onCount + v.add
                            end
                            if (onCount != v.value) then
                                v.value = onCount
                                dirtyAlias = true
                            end
                        end
                    else
                        if (inputs != nil) then
                            if (inputs[v.linkedField].value != v.value) then
                                v.value = inputs[v.linkedField].value
                                dirtyAlias = true
                            end
                        end
                    end
                end
            end
            if (updateIfDirty and dirtyAlias) then
                createUI()
                updateSave()
            end
        end
    end
end

function CheckPlayerColorInUse(targetColor)
    local players = Player.getPlayers()
    for _, player in pairs(players) do
        if player.seated then
            if player.color == targetColor then
                return true -- The color is in use
            end
        end
    end
    return false -- The color is not in use
end