-- ============================================================
-- FUNZIONE: ief_handleChat()
-- ============================================================
function ief_handleChat(message, player)
    if message == "!restart"  then main_restart()  return false end
    if message == "!clear"    then clear()    return false end
    if message == "!minis"    then main_getChildOffsets(player)   return false end
    return false
end

-- ============================================================
-- FUNZIONE: error()
-- ============================================================
function error(warning)
    return fadeOut(warning, nil)
end

-- ============================================================
-- FUNZIONE: fadeOut()
-- ============================================================
function fadeOut(warning, player)
    local alpha = 1

    if player then
        UI.setAttribute("textWarning", "visibility", player.color)
    end

    UI.setAttribute("textWarning", "active", "true")
    UI.setAttribute("textWarning", "text", warning)

    local function step()
        alpha = alpha - 0.05
        if alpha <= 0 then
            UI.setAttribute("textWarning", "active", "false")
            return
        end
        UI.setAttribute("textWarning", "color", "rgba(255,215,0," .. alpha .. ")")
        Wait.time(step, 0.2)
    end

    step()
end

-- ============================================================
-- FUNZIONE: warningToColor()
-- ============================================================

messages = nil
function warningToColor(warning, player, textColor, second)

    local color = textColor == "Yellow" and "#FFD833" or textColor
    messages = warning

    if player then
        UI.setAttribute("playerGameMessage", "Color", color)
        UI.setAttribute("playerGameMessage", "text", warning)
        UI.setAttribute("playerGameMessage", "active", "true")
        UI.setAttribute("playerGameMessage", "visibility", player.color)
    
        Wait.time(function()
            UI.setAttribute("playerGameMessage", "active", "false")
        end, not second and 5 or second)

        Wait.time(function () 
            printToColor("[" .. ENGINE.phase .."] " .. warning, player.color, {1, 1, 1})
        end, 2)
    end
end
-- ============================================================
-- FUNZIONE: warningListToColor()
-- ============================================================
IEF_WARNING_ACTIVE = false

function warningListToColor(warnings, player, textColor, second)

    local color = textColor == "Yellow" and "#FFD833" or textColor

    if player then
        UI.setAttribute("playerGameMessage", "Color", color)
        UI.setAttribute("playerGameMessage", "active", "true")
        UI.setAttribute("playerGameMessage", "visibility", player.color)

        IEF_WARNING_ACTIVE = true
        local a = true

        local function step(i)
            if not IEF_WARNING_ACTIVE then return end

            UI.setAttribute("playerGameMessage", "text", warnings[i])
            if a then
                printToColor("[" .. ENGINE.phase .. "] " .. warnings[i], player.color, {1, 1, 1})
            end

            local nextI = i + 1
            if nextI > 3 then nextI = 1; a = false end

            Wait.time(function()
                step(nextI)
            end, 3)
        end

        step(1)
    end
end
-- ============================================================
-- FUNZIONE: warningToColor()
-- ============================================================
function warning(warning, color)
 
        UI.setAttribute("playerGameMessage", "Color", color)
        UI.setAttribute("playerGameMessage", "text", warning)
        UI.setAttribute("playerGameMessage", "active", "true")
   
    Wait.time(function()
        UI.setAttribute("playerGameMessage", "active", "false")
    end, 5)
end
-- ============================================================
-- FUNZIONE: clear()
-- ============================================================
function clear()
    for i = 0, 250 do
        printToAll("")
    end
end

-- ============================================================
-- FUNZIONE: getVersion()
-- ============================================================
function getVersion()
    return VERSION
end

