-- ============================================================
-- FUNZIONE: roll_btn_all()
-- ============================================================
function roll_btn_all(player, value, id, buttonConfig)

    local slot = (id == BUTTONS.BTN_ARMY1 and 1) or (id == BUTTONS.BTN_ARMY2 and 2) or nil
    if not slot then return false end

    if TURN and TURN.completed and TURN.completed["Army" .. slot] then
        return false
    end

    engine_diceCameraZoom(player, slot)
    return false
end
-- ============================================================
-- FUNZIONE: assign_initiative_btn_all()
-- ============================================================
function assign_initiative_btn_all(player, value, id, buttonConfig)
    
    local winner = ARMY[DICE_CONTEST.winner]    
    local clicker = ARMY[main_getArmyByColor(player)]
    local clicked = ARMY[main_getArmyByButton(id)]
    
    if clicker and winner and clicker.name ~= winner.name then
        warningToColor(clicker.name.." non può usare questo pulsante", player, "Yellow", 5)
        return
    else
        DICE_CONTEST.initiative = clicked
        callHandler("resetTurnForPhase")
        local army = callHandler("getArmySlotByColor", clicked.color)

        TURN.firstArmy = army
        TURN.activeArmy = army

        TURN.completed.Army1 = false
        TURN.completed.Army2 = false
        warning("Iniziativa assegnata a "..clicked.name, player.color)
    end
end

