-- ============================================================
-- FUNZIONE: after_initiative_roll()
-- ============================================================
function before_initiative_roll(phaseName, phase)
    TURN.phase = phaseName
    TURN.completed = { Army1 = false, Army2 = false }
    IEF_DICE_ROLL_TRY[1] = { dadi = 1, soglia = nil }
    IEF_DICE_ROLL_TRY[2] = { dadi = 1, soglia = nil }
    DICE_CONTEST.rolledNumberArmy1 = nil
    DICE_CONTEST.rolledNumberArmy2 = nil
    DICE_CONTEST.winner = nil

    UI.setAttribute("charge_attack_list_army1", "active", "false")
    UI.setAttribute("charge_attack_list_army2", "active", "false")
    UI.setAttribute("charge_defense_list_army1", "active", "false")
    UI.setAttribute("charge_defense_list_army2", "active", "false")
    callHandler("updateCenterPanel")

end
-- ============================================================
-- FUNZIONE: after_initiative_roll()
-- ============================================================
function after_initiative_roll(phaseName, phase)

    engine_diceClearLastRoll(1)
    engine_diceClearLastRoll(2)
end
-- ============================================================
-- FUNZIONE: before_initiative_choice()
-- ============================================================
function before_initiative_choice(phaseName, phase)
    if DICE_CONTEST and DICE_CONTEST.winner then
           UI.setAttribute("iconWinnerArmy"..DICE_CONTEST.winner, "active", "true")
           warning("Il tiro per assegnare l'iniziativa è stato vinto dall'esercito " .. ARMY[DICE_CONTEST.winner].name, "Yellow")
    end

    TURN.phase = phaseName
    TURN.completed = { Army1 = false, Army2 = false }
end
-- ============================================================
-- FUNZIONE: after_initiative_choice()
-- ============================================================
function after_initiative_choice(phaseName, phase)
    if DICE_CONTEST and DICE_CONTEST.winner then
        UI.setAttribute("iconWinnerArmy"..DICE_CONTEST.winner, "active", "false")
    end
end