-- ============================================================
-- WARFORGE IEF — 3_deploy/callbacks.ttslua
-- ============================================================

-- ============================================================
-- FUNZIONE: deploy_btn_army1()
-- ============================================================
function deploy_btn_army1(player, value, id)
    TURN.completed.Army1 = true
    deployment_loadArmySlot(1, player)
    deployment_createArmy1HiddenZones()
    return true
end

-- ============================================================
-- FUNZIONE: deploy_btn_army2()
-- ============================================================
function deploy_btn_army2(player, value, id)
    TURN.completed.Army2 = true
    deployment_loadArmySlot(2, player)
    deployment_createArmy2HiddenZones()
    return true
end

-- ============================================================
-- FUNZIONE: deploy_position_btn_army1()
-- ============================================================
function deploy_position_btn_army1(player, value, id)
    TURN.completed.Army1 = true
    local esito = deployment_validateDeploy(player)
    if esito then
            deployment_destroyArmy1HiddenZones()
    end
    return esito
end

-- ============================================================
-- FUNZIONE: deploy_position_btn_army2()
-- ============================================================
function deploy_position_btn_army2(player, value, id)
    TURN.completed.Army2 = true
    local esito = deployment_validateDeploy(player)
    if esito then
            deployment_destroyArmy2HiddenZones()
    end
    return esito
end
