-- ============================================================
-- WARFORGE IEF — 3_deploy/state.ttslua
-- ============================================================

ARMY = {
    [1] = {
        id     = 1,
        name   = "ARMY1",
        button = BUTTONS.BTN_ARMY1,
        action = ACTION.ARMY1_CLICK,
        color  = COLOR.ARMY1
    },
    [2] = {
        id     = 2,
        name   = "ARMY2",
        button = BUTTONS.BTN_ARMY2,
        action = ACTION.ARMY2_CLICK,
        color  = COLOR.ARMY2
    }
}

IEF_URL_ARMY1 = "https://raw.githubusercontent.com/maxm4004/WARFORGE-IEF/refs/heads/main/generated/tts-armies/ang-army.json"
IEF_URL_ARMY2 = "https://raw.githubusercontent.com/maxm4004/WARFORGE-IEF/refs/heads/main/generated/tts-armies/vik-army.json"

DEPLOYMENT = DEPLOYMENT or {
    initialized = false,
    loading     = false,
    terrain     = "erba_verde",
    army1Hz = nil,
    army2Hz = nil,

    urls = {
        army1 = IEF_URL_ARMY1 or "",
        army2 = IEF_URL_ARMY2 or "",
    },

    armies = {
        [1] = nil,
        [2] = nil
    },

    armyLoaded = {
        [1] = false,
        [2] = false
    },

    armyBusy = {
        [1] = false,
        [2] = false
    },

    scanned = {
        [1] = {},
        [2] = {}
    },

    errors = {}
}

-- ============================================================
-- FUNZIONE: deployment_reset()
-- ============================================================
function deployment_reset()
    DEPLOYMENT.initialized = false
    DEPLOYMENT.loading     = false
    DEPLOYMENT.armies      = { [1] = nil,   [2] = nil   }
    DEPLOYMENT.armyLoaded  = { [1] = false, [2] = false }
    DEPLOYMENT.armyBusy    = { [1] = false, [2] = false }
    DEPLOYMENT.scanned     = { [1] = {},    [2] = {}    }
    DEPLOYMENT.errors      = {}
end

    GAP_DIVERSO = 5 * CM_TO_TTS
    FP_GAP  = 8 * CM_TO_TTS
    FM_GAP  = 8 * CM_TO_TTS
    FL_GAP = 9 * CM_TO_TTS
    CP_GAP  = 9 * CM_TO_TTS

DEPLOYMENT.fogArm1 = [[
{
  "Name": "FogOfWarTrigger",
  "Transform": {
    "posX": -0.151100159,
    "posY": 3.95,
    "posZ": -33.0519753,
    "rotX": 0.0,
    "rotY": 0.0,
    "rotZ": 0.0,
    "scaleX": 110.555443,
    "scaleY": 5.1,
    "scaleZ": 22.224226
  },
  "Nickname": "FogOfWarTrigger_Army1",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 0.856,
    "g": 0.09999997,
    "b": 0.09399996,
    "a": 0.2532052
  },
  "Tags": [
    "Army1"
  ],
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "FogColor": "Red",
  "FogHidePointers": true,
  "FogReverseHiding": false,
  "FogSeethrough": false,
  "LuaScript": "",
  "LuaScriptState": "",
  "XmlUI": ""
}
]]

DEPLOYMENT.fogArmy2 = [[
{
  "Name": "FogOfWarTrigger",
  "Transform": {
    "posX": 0.42,
    "posY": 3.95,
    "posZ": 33.05,
    "rotX": 0.0,
    "rotY": 0.0,
    "rotZ": 0.0,
    "scaleX": 110.555443,
    "scaleY": 5.1,
    "scaleZ": 22.224226
  },
  "Nickname": "FogOfWarTrigger_Army2",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 0.094,
    "g": 0.856,
    "b": 0.094,
    "a": 0.2532052
  },
  "Tags": [
    "Army2"
  ],
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "FogColor": "Green",
  "FogHidePointers": true,
  "FogReverseHiding": false,
  "FogSeethrough": false,
  "LuaScript": "",
  "LuaScriptState": "",
  "XmlUI": ""
}
]]