-- ============================================================
-- FUNZIONE: charge(obj)
-- ============================================================
function charge(obj)
    obj.createButton({
        click_function = "",
        function_owner = Global,
        label = "CARICA",
        position = {0, 0.1, -1.8},
        rotation = {0, 180, 0},
        width = 500, height = 400, font_size = 100,
    })
end