-- ============================================================
-- FUNZIONE: charge_declare_btn_army1(player, value, id, buttonConfig)
-- Conferma "Dichiarazioni Completate" per Army1.
-- ============================================================
function charge_declare_btn_army1(player, value, id, buttonConfig)
    callHandler("advanceTurnAfterClick", BUTTONS.BTN_ARMY1)
    return true
end

-- ============================================================
-- FUNZIONE: charge_declare_btn_army2(player, value, id, buttonConfig)
-- Conferma "Dichiarazioni Completate" per Army2.
-- ============================================================
function charge_declare_btn_army2(player, value, id, buttonConfig)
    callHandler("advanceTurnAfterClick", BUTTONS.BTN_ARMY2)
    return true
end