-- ============================================================
-- FUNZIONE: before_sitting()
-- ============================================================
function before_sitting(phaseName, phase)
    TURN.phase = phaseName
    linea_field   = false
    linee_deploy  = false
    linee_settori = false

    FIELD_STATE.orientamento1 = orientamentoArmy1
    FIELD_STATE.orientamento2 = orientamentoArmy2
    FIELD_STATE.army1Elements = FIELD_ELEMENTS_BY_ORIENTAMENTO[orientamentoArmy1]
    FIELD_STATE.army2Elements = FIELD_ELEMENTS_BY_ORIENTAMENTO[orientamentoArmy2]

    callHandler("aggiornaLinee")
end
-- ============================================================
-- FUNZIONE: after_sitting()
-- ============================================================
function after_sitting(phaseName, phase) end