-- ============================================================
-- WARFORGE IEF — Sitting
-- v1.0.0
-- ============================================================


require("rulesets.imperifeudi.1_sitting.callbacks")
require("rulesets.imperifeudi.1_sitting.hooks")
require("rulesets.imperifeudi.1_sitting.lib")
require("rulesets.imperifeudi.1_sitting.state")
require("rulesets.imperifeudi.1_sitting.phase")

