-- ============================================================
-- FUNZIONE: roll_btn_all()
-- ============================================================
function move_btn_army1(player, value, id, buttonConfig)
    callHandler("advanceTurnAfterClick", BUTTONS.BTN_ARMY1)
    return true
end
-- ============================================================
-- FUNZIONE: roll_btn_all()
-- ============================================================
function move_btn_army2(player, value, id, buttonConfig)
    callHandler("advanceTurnAfterClick", BUTTONS.BTN_ARMY2)
    return true
end
