function before_field(phaseName, phase)

    print("before_field")
    TURN.phase = phaseName
    FIELD_STATE = { diceResult=nil, numElements=nil, army1Elements=0, army2Elements=0, tieBreaker=false, tbResult1=nil, tbResult2=nil }
    --linea_field = true
    linee_settori = true
    callHandler("aggiornaLinee")
end
-- ============================================================
-- FUNZIONE: after_field()
-- ============================================================
function after_field(phaseName, phase)
    TURN.completed = { Army1 = false, Army2 = false }
end
-- ============================================================
-- FUNZIONE: before_field_roll()
-- ============================================================
function before_field_roll(phaseName, phase)
    TURN.phase = phaseName
end
-- ============================================================
-- FUNZIONE: after_field_roll()
-- ============================================================
function after_field_roll(phaseName, phase)
    TURN.completed = { Army1 = false, Army2 = false }
end
-- ============================================================
-- FUNZIONE: before_field_done()
-- ============================================================
function before_field_done(phaseName, phase)
    if DEBUG then print("before_field_done") end    
    TURN.phase = phaseName
    callHandler("engine_resetState")
end
-- ============================================================
-- FUNZIONE: after_field_done()
-- ============================================================
function after_field_done(phaseName, phase)
    if DEBUG then print("after_field_done") end
    
    TURN.completed = { Army1 = false, Army2 = false }
    linea_field = false
   
    callHandler("lockTerrain")
    callHandler("aggiornaLinee")
end