-- 2_field/phase.ttslua
function field_phase()
    return {        
        FIELD = {
            title = "CAMPO DI BATTAGLIA",
            desc  = "Confermare l'orientamento del proprio esercito per il numero \n degli elementi sul terreno",
            before = "before_field",
            after  = "after_field",
            allowedActions = { ACTION.ARMY1_CLICK, ACTION.ARMY2_CLICK },
            render = "2BtnClick",
            enforceOwnership = true,
            inputMode = "OWNER",
            buttons = {
                BTN_ARMY1 = { action="ARMY1_CLICK", label=orientamentoArmy1 .." (" .. FIELD_ELEMENTS_BY_ORIENTAMENTO[orientamentoArmy1] .. " elementi)", textColor="White", color="Red",   callback="field_confirm_army1" },
                BTN_ARMY2 = { action="ARMY2_CLICK", label=orientamentoArmy2 .." (" .. FIELD_ELEMENTS_BY_ORIENTAMENTO[orientamentoArmy2] .. " elementi)", textColor="White", color="Green", callback="field_confirm_army2" },
            },
            transitions = {
                { to="FIELD_ROLL", conditions={ COND.BOTH_PLAYERS_SELECTED } }
            }
        },
        FIELD_ROLL = {
            title = "CAMPO DI BATTAGLIA",
            desc  = "Tira i dadi fisici (bottone sul tavolo) per determinare il tipo di ogni elemento",
            before = "before_field_roll",
            after  = "after_field_roll",
            allowedActions = { ACTION.ARMY1_CLICK, ACTION.ARMY2_CLICK },
            render = "2BtnClick",
            enforceOwnership = true,
            inputMode = "OWNER",
            buttons = {
                BTN_ARMY1 = { action="ARMY1_CLICK", label="Vai al lancio", textColor="White", color="Red",   callback="field_rollDicesForElementsArmy1" },
                BTN_ARMY2 = { action="ARMY2_CLICK", label="Vai al lancio", textColor="White", color="Green", callback="field_rollDicesForElementsArmy2" },
            },
            transitions = {
                { to="FIELD_DONE", conditions={ COND.confirm_immediate } }
            }
        },
        FIELD_DONE = {
            title = "CAMPO DI BATTAGLIA",
            desc  = "Posiziona gli elementi sul tavolo",
            before = "before_field_done",
            after  = "after_field_done",
            allowedActions = { ACTION.ARMY1_CLICK, ACTION.ARMY2_CLICK },
            render = "fieldConfirm",
            enforceOwnership = true,
            inputMode = "OWNER",
            buttons = {
                BTN_ARMY1 = { action="ARMY1_CLICK", label="Fatto", textColor="White", color="Red",   callback="field_btn_army1" },
                BTN_ARMY2 = { action="ARMY2_CLICK", label="Fatto", textColor="White", color="Green", callback="field_btn_army2" },
            },
            transitions = {
                { to="DEPLOY_SPAWN", conditions={ COND.BOTH_PLAYERS_SELECTED } }
            }
        }
    }
end
