-- 2_field/phase.ttslua
function field_phase()
    return {
        FIELD = {
            title = "CAMPO DI BATTAGLIA",
            desc  = "Tira un dado per stabilire il numero degli elementi sul tavolo",
            before = "before_field",
            after  = "after_field",
            allowedActions = { ACTION.CONFIRM },
            render = "1BtnClickAndRoll",
            enforceOwnership = true,
            inputMode = "OWNER",
            buttons = {
                      BTN_SINGLE = { action="CONFIRM", label="Tira un dado", textColor="Black", color="Grey", callback="field_rollDice" }             
            },
            transitions = {
                { to="FIELD_ROLL", conditions={ COND.CONFIRM_READY } }
            }
        },
        FIELD_ROLL = {
            title = "CAMPO DI BATTAGLIA",
            desc  = "Tira il dado per determinare quanti elementi di terreno posizionare",
            before = "before_field_roll",
            after  = "after_field_roll",
            allowedActions = { ACTION.ARMY1_CLICK, ACTION.ARMY2_CLICK },
            render = "tiebreaker",
            enforceOwnership = true,
            inputMode = "OWNER",
            buttons = {
                BTN_ARMY1 = { action="ARMY1_CLICK", label="Tira dado", textColor="White", color="Red",   callback="field_tieBreakerArmy1" },
                BTN_ARMY2 = { action="ARMY2_CLICK", label="Tira dado", textColor="White", color="Green", callback="field_tieBreakerArmy2" },
            },
            transitions = {
                { to="FIELD_DONE", conditions={ COND.confirm_immediate } }
            }
        },
        FIELD_DONE = {
            title = "CAMPO DI BATTAGLIA",
            desc  = "Posiziona gli elementi sul tavolo",
            before = "before_field_done",
            after  = "after_field_done",
            allowedActions = { ACTION.ARMY1_CLICK, ACTION.ARMY2_CLICK },
            render = "fieldConfirm",
            enforceOwnership = true,
            inputMode = "OWNER",
            buttons = {
                BTN_ARMY1 = { action="ARMY1_CLICK", label="Fatto", textColor="White", color="Red",   callback="field_btn_army1" },
                BTN_ARMY2 = { action="ARMY2_CLICK", label="Fatto", textColor="White", color="Green", callback="field_btn_army2" },
            },
            transitions = {
                { to="DEPLOY_SPAWN", conditions={ COND.BOTH_PLAYERS_SELECTED } }
            }
        }
    }
end
