-- 2_field/phase.ttslua
function field_phase()
    return {        
            FIELD = {
                title = "CAMPO DI BATTAGLIA",
                desc  = "NUMERO CARTE TERRENO",
                before = "before_field",
                after  = "after_field",
                allowedActions = { ACTION.ARMY1_CLICK, ACTION.ARMY2_CLICK },
                render = "2BtnClick",
                enforceOwnership = true,
                inputMode = "OWNER",
                buttons = {
                    BTN_ARMY1 = { action="ARMY1_CLICK", label= FIELD_ELEMENTS_BY_ORIENTAMENTO[orientamentoArmy1] .. " Carte", textColor="White", color="Red",   callback="field_readyArmy1" },
                    BTN_ARMY2 = { action="ARMY2_CLICK", label= FIELD_ELEMENTS_BY_ORIENTAMENTO[orientamentoArmy2] .. " Carte", textColor="White", color="Green", callback="field_readyArmy2" },
                },
                transitions = {
                    { to="FIELD_ROLL", conditions={ COND.BOTH_PLAYERS_SELECTED } }
                }
            },
            FIELD_ROLL = {
                title = "CAMPO DI BATTAGLIA",
                desc  = "TIRA I DADI PER ASSEGANRE AD OGNI CARTA UN TIPO DI TERRENO",
                before = "before_field_roll",
                after  = "after_field_roll",
                allowedActions = { ACTION.ARMY1_CLICK, ACTION.ARMY2_CLICK },
                render = "2BtnClick",
                enforceOwnership = true,
                inputMode = "OWNER",
                buttons = {
                BTN_ARMY1 = { action = "ARMY1_CLICK", label = "Tira per Carta 1/" .. (FIELD_STATE.army1Elements or 0), textColor = "White", color = "Red", callback = "field_rollFieldElement" },
                    BTN_ARMY2 = { action="ARMY2_CLICK", label="Tira per Carta 1/" .. (FIELD_STATE.army2Elements or 0), textColor="White", color="Green", callback="field_rollFieldElement" },
                },
                transitions = {
                    { to="FIELD_BLOCK", conditions={ COND.BOTH_PLAYERS_SELECTED } }
                }
            },
            FIELD_BLOCK = {
                title = "CAMPO DI BATTAGLIA",
                desc  = "ASSEGNA AD OGNI CARTA UNA ZONA SUL TAVOLO",
                before = "before_field_block",
                after  = "after_field_block",
                allowedActions = { ACTION.ARMY1_CLICK, ACTION.ARMY2_CLICK },
                render = "2BtnClick",
                enforceOwnership = true,
                inputMode = "OWNER",
                buttons = {
                    BTN_ARMY1 = { action="ARMY1_CLICK", label="Assegna Zona", textColor="White", color="Red",   callback="field_rollBlockZoom" },
                    BTN_ARMY2 = { action="ARMY2_CLICK", label="Assegna Zona", textColor="White", color="Green", callback="field_rollBlockZoom" },
                },
                transitions = {
                    { to="FIELD_DONE", conditions={ COND.BOTH_PLAYERS_SELECTED } }
                }
            },
            FIELD_DONE = {
                title = "CAMPO DI BATTAGLIA",
                desc  = "OGNI CARTA SUL TAVOLO DIVENTA UNN ELEMENTO 3D",
                before = "before_field_done",
                after  = "after_field_done",
                allowedActions = { ACTION.ARMY1_CLICK, ACTION.ARMY2_CLICK },
                render = "fieldConfirm",
                enforceOwnership = true,
                inputMode = "OWNER",
                buttons = {
                    BTN_ARMY1 = { action="ARMY1_CLICK", label="Genera Elementi 3D", textColor="White", color="Red",   callback="field_done_army1" },
                    BTN_ARMY2 = { action="ARMY2_CLICK", label="Genera Elementi 3D", textColor="White", color="Green", callback="field_done_army2" },
                },
                transitions = {
                    { to="FIELD_POSITIONING_TERRAIN", conditions={ COND.BOTH_PLAYERS_SELECTED } }
                }
            },
            FIELD_POSITIONING_TERRAIN = {
                title = "CAMPO DI BATTAGLIA",
                desc  = "POSIZIONA E ORIENTA GLI ELEMENTI NELLA ZONA ASSEGNATA",
                before = "before_field_positioning_terrain",
                after  = "after_field_positioning_terrain",
                allowedActions = { ACTION.ARMY1_CLICK, ACTION.ARMY2_CLICK },
                render = "2BtnClick",
                enforceOwnership = true,
                inputMode = "OWNER",
                buttons = {
                    BTN_ARMY1 = { action="ARMY1_CLICK", label="Posiziona e Orienta", textColor="White", color="Red",   callback="field_readyPositioning1" },
                    BTN_ARMY2 = { action="ARMY2_CLICK", label="Posiziona e Orienta", textColor="White", color="Green", callback="field_readyPositioning2" },
                },
                transitions = {
                    { to="DEPLOY_SPAWN", conditions={ COND.BOTH_PLAYERS_SELECTED } }
                }
            }
        }
end
