diceUrls = {
    [1] = "https://raw.githubusercontent.com/maxm4004/Tabletop-Simulator-Lua/refs/heads/main/dice/1d6.png",
    [2] = "https://raw.githubusercontent.com/maxm4004/Tabletop-Simulator-L/uarefs/heads/main/dice/2d6.png",
    [3] = "https://raw.githubusercontent.com/maxm4004/Tabletop-Simulator-Lua/refs/heads/main/dice/3d6.png",
    [4] = "https://raw.githubusercontent.com/maxm4004/Tabletop-Simulator-Lua/refs/heads/main/dice/4d6.png",
    [5] = "https://raw.githubusercontent.com/maxm4004/Tabletop-Simulator-Lua/refs/heads/main/dice/5d6.png",
    [6] = "https://raw.githubusercontent.com/maxm4004/Tabletop-Simulator-Lua/refs/heads/main/dice/6d6.png"
}

-- ============================================================
-- FIELD STATE
-- Stato runtime della fase FIELD
-- ============================================================

  orientamentoArmy1 = "Fanteria"    -- hardcoded, arriverà da armyData.orientamento
  orientamentoArmy2 = "Bilanciato"  -- hardcoded, arriverà da armyData.orientamento


FIELD_STATE = FIELD_STATE or {
    diceResult    = nil,
    numElements   = nil,
    army1Elements = 0,
    army2Elements = 0,
    tieBreaker    = false,
    tbResult1     = nil,
    tbResult2     = nil,
    elementsRolled = { [1] = 0, [2] = 0 },
}

IEF_TERRAIN_BAG = "a87f74"

IEF_FIELD_CARD_BAG  = {
        ["Aperto"]           = "8178f8",
        ["Rotto"]            = "7bc71a",
        ["Difficile"]        = "89916e",
        ["Intransitabile"]   = "724f2a",
        ["Fiume"]            = "58fc46"    
}

IEF_FIELD_CARD_TEMPLATE = {}

FIELD_ELEMENTS_BY_ORIENTAMENTO = {
    ["Fanteria"]  = 4,
    ["Bilanciato"] = 3,
    ["Cavalleria"] = 2
}


IEF_FIELD_CARD_POS = {
    [1] = {
        { x = -77.51, y = 1.00, z = -53.29 },
        { x = -70.74, y = 1.00, z = -53.29 },
        { x = -64.02, y = 1.00, z = -53.29 },
        { x = -57.58, y = 1.00, z = -53.29 },
    },
    [2] = {
        { x = 77.51, y = 1.00, z = 53.29 },
        { x = 70.74, y = 1.00, z = 53.29 },
        { x = 64.02, y = 1.00, z = 53.29 },
        { x = 57.58, y = 1.00, z = 53.29 },
    },
}

IEF_FIELD_CARD_ROT = {
    [1] = { x = 0, y = 180, z = 0 },
    [2] = { x = 0, y = 0,   z = 0 },
}

army1_elements = {}
army2_elements = {}